### ISSUE TITLE
챌린지리스트 화면 스타일

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#10]
![image](https://user-images.githubusercontent.com/14939610/33248665-79b8a87c-d369-11e7-9127-0925edf380f8.png)

- [ ] 위 이미지의 지역선택과 챌린지 클래스별, 타입별 폰트 사이즈 확인부탁드립니다.

- [ ] 각 셀렉박스의 드롭다운 화살표의 상하 여백 확인부탁드립니다. 

![image](https://user-images.githubusercontent.com/14939610/33248712-c0a76584-d369-11e7-8e74-97a6a1f9bb6e.png)

- [ ] #9 의 이슈와 같은내용으로 리스트의 폰트와 그림자 스타일 확인 부탁드립니다.

![image](https://user-images.githubusercontent.com/14939610/33248770-251a27fe-d36a-11e7-810e-86aa939697af.png)

- [ ] 셀렉박스 드롭다운 디자인 스타일, 크기(드롭다운 박스의 너비가 더 넓어보입니다)도 확인부탁드립니다. 

- [ ] 펼침화면에서 화살표 아이콘 방향도 바뀝니다.

**Comment by applicatteam** [comment]
이슈가 없다면 닫아주세요
