### ISSUE TITLE
유저 출생년도 선택시 문제

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#102]
- [x] 유저가 최초 챌린지 참가시 출생년도 선택시, 아래 이미지와 같이 '0000'년도를 보여주는 형태입니다. '2000'년도가 최초에 표시되는 출생년도로 요청드렸던 것은 반영되었지만, 선택할 수 있는 출생년도의 범위는 (현재의 연도 -1)부터 시작하는 것으로 요청드립니다.  최초에 표시되는 출생년도는 '2000'년도부터로 그대로 두시고, 출생년도의 범위를 변경해주세요.

![default](https://user-images.githubusercontent.com/34014924/35091616-622a4a54-fc80-11e7-882e-15ab2dd816b2.jpg)

**Comment by applicatteam** [comment]
- [ ] 유저가 최초 챌린지 참가시 출생년도 선택시, 아래 이미지와 같이 '0000'년도를 보여주는 형태입니다. '2000'년도가 최초에 표시되는 출생년도로 요청드렸던 것은 반영되었지만, 선택할 수 있는 출생년도의 범위는 (현재의 연도 -1)부터 시작하는 것으로 요청드립니다.  최초에 표시되는 출생년도는 '2000'년도부터로 그대로 두시고, 출생년도의 범위를 변경해주세요.

**Comment by Hyungseok-Seong** [comment]
확인되었습니다.
