### ISSUE TITLE
아이폰5 지원 안되는 문제

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#105]
![image](https://user-images.githubusercontent.com/14939610/35136108-e22d71aa-fd24-11e7-9d7f-4dcde8c10c6d.png)

- [x] 아이폰5 기기에서 이렇게 나옵니다.

**Comment by applicatteam** [comment]
걸음수 측정 지원 불가에 대해 전달드립니다. 

ios에 경우 걸음수 측정에 필요한 pedometer는 motion co-processor chip이 있는 iphone5s 이상 기기에서만 사용가능 합니다..
참조 문서 :  https://en.wikipedia.org/wiki/Apple_motion_coprocessors

android에 경우 pedometer는  전달드린 이미지내에 정리된 기종부터 지원이 됩니다.
![image](https://user-images.githubusercontent.com/15938046/35372096-6f02dd8a-01db-11e8-8138-219ad3acbb1f.png)
