### ISSUE TITLE
QR챌린지-상세페이지에서 체크인포인트의 이름이 긴 경우 나타나는 문제

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#106]
- [x] QR챌린지-상세페이지에서 체크인포인트의 이름이 긴 경우 아래 이미지처럼 표시됩니다. 체크인포인트의 이름이 'QR코드 스캔 여부 체크박스' 영역까지 덮어버린 상황입니다. QR챌린지에서 체크인포인트 이름에 표시되는 글자 수 제한이 있으면 알려주세요. 글자 수 제한을 알려주시면, 챌린지 기획시 이에 유념하여 체크인포인트를 잡고 admin에서 입력하도록 하겠습니다.

![qr](https://user-images.githubusercontent.com/34014924/35138634-e3d21606-fd32-11e7-819f-b09c2ea78063.jpg)

**Comment by applicatteam** [comment]
- [ ] QR챌린지-상세페이지에서 체크인포인트의 이름이 긴 경우 아래 이미지처럼 표시됩니다. 체크인포인트의 이름이 'QR코드 스캔 여부 체크박스' 영역까지 덮어버린 상황입니다. QR챌린지에서 체크인포인트 이름에 표시되는 글자 수 제한이 있으면 알려주세요. 글자 수 제한을 알려주시면, 챌린지 기획시 이에 유념하여 체크인포인트를 잡고 admin에서 입력하도록 하겠습니다.

**Comment by Hyungseok-Seong** [comment]
180320
글자 수 제한은 #170 에서 전달받을 예정입니다.
