### ISSUE TITLE
지역선택 화면 스타일

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#11]
![image](https://user-images.githubusercontent.com/14939610/33249256-f3b7143a-d36c-11e7-9010-ac916103abcd.png)

- [x] 챌린지 리스트에서 지역선택시 나오는 첫화면은 위의 왼쪽과 같은 화면으로 각 지역이 닫혀있는 형태입니다. 보여주신 화면은 열려있는 화면으로 나오는데 확인부탁드립니다.

![image](https://user-images.githubusercontent.com/14939610/33249720-68d2a8f4-d36f-11e7-8c1c-475562a8eeec.png)

- [x] 전체적인 컬러와 ,폰트사이즈, 폰트컬러 확인 부탁드립니다.

- [x] 오른쪽 외곽 박스 라인이 깔끔하지 않게 떨어지는 부분 확인부탁드립니다.

- [x] 한 지역을 눌러 펼쳐졌을때 화살표 방향도 바뀝니다.
  
-------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/14939610/34553722-6e69e550-f16c-11e7-9df5-d9234078af85.png)

- [x] 1.전체적인 컬러와 ,폰트사이즈, 폰트컬러 확인 부탁드립니다.

- [x] 2. UI깨진부분 확인바랍니다.

- [x] 3.선택박스가 어긋나네요.

- [x] 4. 선택된 지역  영역 오른쪽의 확인아이콘도 위의 리스트처럼 펼침, 닫기 기능이 있어야합니다.

- [x] 5. 선택된 지역의 박스 디자인 제플린 참고하여 여백 맞춰주세요

- [x] 펼침 닫기 아이콘의 애니메이션은 회전적용은 빼주세요. 아이콘은 둘다 동일한 위치에 있게해주세요. 회전하면서 왼쪽으로 이동합니다. 우측 여백 맞춰주세요. 다른 곳의 이 기능의 스타일도 통일해주세요

**Comment by applicatteam** [comment]
이슈가 없다면 닫아주세요
