### ISSUE TITLE
번역에 필요한 문구 전달드립니다.

### ISSUE THREAD

**Issue by applicatteam** [gracemj/getwalk#115]
번역 필요합니다

걸음수 측정을 지원하지 않는 기기입니다
걸음 수 측정 권한이 없습니다. 설정에서 허용해주세요

위치정보를 불러올 수 없습니다. 설정에서 위치권한을 허용해주세요.
위치정보사용권한을 항상 허용해주세요

디바이스 정보를 불러오지 못했습니다. 설정에서 다시 설정해주세요.
디바이스를 등록하는데 실패했습니다. 설정에서 다시 시도해주세요.

주소를 찾을 수 없습니다.
우편번호를 입력해주세요.

걸음 수 측정 권한이 없습니다

**Comment by Hyungseok-Seong** [comment]
걸음수 측정을 지원하지 않는 기기입니다
歩数測定ができない端末です

걸음 수 측정 권한이 없습니다. 설정에서 허용해주세요
歩数測定ができません。端末設定から「モーションとフィットネス」をONにしてください

위치정보를 불러올 수 없습니다. 설정에서 위치권한을 허용해주세요.
位置情報を取得できません。端末設定から位置情報を「常に許可」に設定してください

위치정보사용권한을 항상 허용해주세요
端末設定から位置情報を「常に許可」に設定してください

디바이스 정보를 불러오지 못했습니다. 설정에서 다시 설정해주세요.
デバイス情報の取得に失敗しました。端末設定から再度設定してください

디바이스를 등록하는데 실패했습니다. 설정에서 다시 시도해주세요.
デバイスの登録に失敗しました。端末設定から再度設定してください

주소를 찾을 수 없습니다.
住所が見つかりません

우편번호를 입력해주세요.
郵便番号を入力してください

걸음 수 측정 권한이 없습니다
歩数計測ができません
