### ISSUE TITLE
사이드메뉴 스타일

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#12]
![image](https://user-images.githubusercontent.com/14939610/33251662-c7bb1098-d37b-11e7-932e-aeb039e0f208.png)

- [x] 프로필 이미지 육각형 형태가 깨져보입니다.  

- [x] 레벨, 누적걸음수 폰트 컬러가 진합니다.

- [x] 숫자폰트 두께가 두껍습니다. 폰트사이즈와 두께 확인부탁드립니다.

- [x] k는 대문자 K로 바꿔주세요

- [x] 아래 SNS아이콘 크기 확인부탁드립니다. 지금은 인스타그램이 너무 작아보이네요

- [x] 아래 카피라이트 폰트컬러 확인부탁드립니다.

**Comment by applicatteam** [comment]
이슈가 없다면 닫아주세요
