### ISSUE TITLE
텍스트 교정

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#126]
- [ ] 얼럿 메시지 및 푸시 알림, Notification에 들어가 있는 각종 일본어 텍스트들 중에 아래와 같이 오기가 되었거나, 매끄럽지 못한 표현이 있는 것으로 보입니다. 개발에 사용된 일본어 텍스트들을 전부 전달해주시면, 다시 교정하여 전달드리겠습니다. 부탁드립니다.

![default](https://user-images.githubusercontent.com/34014924/35952336-dd0b35ce-0cc2-11e8-877e-a8426a07bd75.jpg)

**Comment by applicatteam** [comment]
[translation.xlsx](https://github.com/gracemj/getwalk/files/1715089/translation.xlsx)

이형식에 맞춰서 전달 부탁드립니다.
