### ISSUE TITLE
QR챌린지 QR코드 스캔시 얼럿

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#129]
- [ ] QR챌린지 참여시, 유저가 이미 스캔했던 QR코드를 다시 스캔하는 경우에 나오는 메시지가 아래처럼 
一時的な問題が発生しました(일시적인 문제가 발생했습니다) 으로 나오고 있습니다. 이 멘트가 아니라 다음의 멘트(이미 스캔한 QR코드입니다)로 변경해주세요  既にスキャンしたQRコードです 
- [ ] QR챌린지 참여시, 유저가 스캔하는 QR코드가 챌린지 관련 QR이 아니라 전~~혀 관계 없는 QR코드를 스캔하면 자동적으로 카메라가 닫히게 되고 있습니다. 이 상황에서 얼럿을 요청하셨기에 전달드렸는데 아직 반영이 안 된 것 같습니다. 다음의 멘트(대상 밖의 QR코드입니다)가 나오도록 반영해주세요 対象外のQRコードです

![qr](https://user-images.githubusercontent.com/34014924/36414414-8b4f1028-1665-11e8-950f-4a68c581c445.jpg)

**Comment by hannut91** [comment]
수정하였습니다.
