### ISSUE TITLE
문의 화면스타일

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#13]
![image](https://user-images.githubusercontent.com/14939610/33251887-a5ff5dc2-d37d-11e7-9dea-f0e6f8b7b991.png)

- [x] 상단의 타이틀 폰트 두께 확인부탁드립니다.

- [x] 각 리스트 우측 화살표 방향 확인부탁드립니다.

- [x] 리스트 배경의 컬러가 달라보이는데 확인부탁드립니다.

**Comment by gracemj** [comment]
![image](https://user-images.githubusercontent.com/14939610/34709987-e4ee2594-f55c-11e7-811e-0dccd60744f1.png)

- [ ] 아직 내용이 없어서 해당 내용이 안나오는건가요?

**Comment by applicatteam** [comment]
이슈가 없다면 닫아주세요
