### ISSUE TITLE
admin 에서 sponsor user 생성시 invalid request 

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#132]
- [x] admin web에서 sponsor user를 생성하는 방법은 다음과 같은 것으로 알고 있습니다. 1) Sponsor management 에서 sponsor를 먼저 생성 2) User management 에서 새로운 유저 생성시 authority를 sponsor로 지정하고, ID 생성. 여기서, 2)의 단계에서 모든 사항을 이미지처럼 입력했음에도 invalid request가 나오고 있습니다. 확인해 주세요.

![sponsor user](https://user-images.githubusercontent.com/34014924/36455948-de90d37c-16e5-11e8-817f-777bc756a0dd.PNG)

**Comment by hannut91** [comment]
![image](https://user-images.githubusercontent.com/14071105/36458643-3548a3c2-16f3-11e8-9419-e89974731f96.png)
이미 logos@test.com으로 USER로 만드신것으로 확인이 됩니다.

**Comment by Hyungseok-Seong** [comment]
확인되었습니다.
이슈 닫겠습니다.
