### ISSUE TITLE
iOS device 흔들 때 나오는 OS 얼럿

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#133]
- [ ] iOS device를 흔들 때 아래와 같은 얼럿이 나옵니다.  iOS에서 제공하는 기능임은 알고 있습니다. 그러나,  유저가 type 하는 상황에서 나오는 게 일반적인 얼럿이므로, GetWalk app에서는 보이지 않는 것이 맞다고 생각합니다. 확인 후 의견 주세요.

![shake_alert](https://user-images.githubusercontent.com/34014924/36466680-a9832ab6-171e-11e8-9826-64737eee2aef.jpg)

**Comment by hannut91** [comment]
iOS에서 동작하는것을 앱에서 막을 수는 없습니다.
