### ISSUE TITLE
마이리워드 - 이미지가 나오지 않아요

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#134]
- [ ] 마이리워드 - 이미지가 나오지 않아요

![-](https://user-images.githubusercontent.com/34014924/36469652-50425f1e-172b-11e8-96a3-0cd8b86838b8.jpg)

**Comment by hannut91** [comment]
![screen](https://user-images.githubusercontent.com/14071105/36477029-1db16a1e-1743-11e8-8cd0-962d41b48a71.png)
문제가 발견되지 않아 파악이 어렵습니다. 계정정보 알려주시면 다시 한번 확인해보겠습니다.

**Comment by Hyungseok-Seong** [comment]
해당 문제가 발생한 계정 정보는 아래와 같습니다:

ID: sh@smart-routine.com
PW: getwalk2017
