### ISSUE TITLE
유저가 챌린지에 참여하여 상품 획득 성공/획득 실패에 따른 이미지 표시 

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#135]
- [x] Storyboard 94p 에 설명이 나와있습니다. 유저가 챌린지에 참여하여 상품을 획득한 경우 마이챌린지 리스트에서 표시되는 이미지와 상품 획득에 실패한 경우 표시되는 이미지가 다릅니다. 현재는 모두 획득에 실패한 이미지만 표시되고 있습니다.

![-](https://user-images.githubusercontent.com/34014924/36512664-c0e6079c-17ae-11e8-9ecf-5f26f9e7d8e9.jpg)

**Comment by hannut91** [comment]
상품울 구매하면 웃는 이미지, 구매하지 않앗으면 우는 이미지가 맞나요?

**Comment by Hyungseok-Seong** [comment]
네

챌린지 달성 여부와 관계 없이,
유저가 해당 챌린지의 상품을 결제하여 마이 리워드에 상품 정보가 넘어가면 웃는 이미지입니다.

유저가 달성했든 아니든, 결과적으로 상품을 결제하지 않거나, 상품을 얻지 못했다면
우는 이미지입니다.

**Comment by hannut91** [comment]
상품을 수령하였을 때 웃는이미지, 상품을 획득하지 않앗을 때 우는이미지로 개발이 되어있어서 
상품울 구매하면 웃는 이미지, 구매하지 않앗으면 우는 이미지로 변경하였습니다.

**Comment by Hyungseok-Seong** [comment]
네

유저가 상품을 획득하여 마이 리워드로 해당 챌린지의 상품이 표시되는 경우 웃는 이미지로 표시되는 것으로 변경하신 거라면 맞습니다.

참고로, 상품 수령은 패스코드를 입력받아 오프라인에서 유저가 상품을 실수령하는 것을 의미합니다.

**Comment by Hyungseok-Seong** [comment]
아직 마이챌린지에서 제대로 유저가 참여한 종료챌린지가 표시되지 않고 있어 확인이 어렵습니다.

**Comment by applicatteam** [comment]
종료 챌린지 표시 되는 부분 수정 완료되었습니다. 스크린샷 첨부 해드립니다. android는  OS ver 8.0.0 / V30기종의 스크린샷이며 , iOS는 iphone6S+ 11.2.5 / iphone 6 : 11.2.6  입니다.
![image uploaded from ios 1](https://user-images.githubusercontent.com/15938046/37393487-9012dc6a-27b4-11e8-8116-1b03c191ecc3.jpg)
iphone6S+ / OS 11.2.5
![111](https://user-images.githubusercontent.com/15938046/37393519-a74d005e-27b4-11e8-9a89-15ceacd9494e.png)
iphone 6 / 11.2.6
![screenshot_2018-03-14-18-18-58](https://user-images.githubusercontent.com/15938046/37393588-d1e3f700-27b4-11e8-86e1-05e7b2b20ff5.png)
V30 / android 8.0.0
