### ISSUE TITLE
동일한 푸시 알림이 3개 왔습니다.

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#137]
- [ ] 동일한 푸시 알림이 3개 왔습니다.  확인해주세요. 
- [ ] 유저에게 참가중인 챌린지의 현황을 알려주는 푸시 메시지는 개인챌린지의 경우 오전 8시, QR챌린지의 경우 오후 2시입니다. 이 점도 확인 부탁드려요.

![3](https://user-images.githubusercontent.com/34014924/36571277-4e02f854-1879-11e8-9dbb-6ae177205097.jpg)
![3](https://user-images.githubusercontent.com/34014924/36571278-4e2b88be-1879-11e8-981a-661dfb9d3754.jpg)

**Comment by hannut91** [comment]
- [ ] 동일한 푸시 알림이 3개 왔습니다. 확인해주세요.
- [ ] 유저에게 참가중인 챌린지의 현황을 알려주는 푸시 메시지는 개인챌린지의 경우 오전 8시, QR챌린지의 경우 오후 2시입니다. 이 점도 확인 부탁드려요.
=> 어떤점을 확인해야 하는건가요? 구체적으로 말씀부탁드립니다.

**Comment by Hyungseok-Seong** [comment]
- [ ] 동일한 푸시 알림이 3개 왔습니다. 확인해주세요.
- [ ] 유저에게 참가중인 챌린지의 현황을 알려주는 푸시 메시지는 개인챌린지의 경우 오전 8시, QR챌린지의 경우 오후 2시입니다. 이 점도 확인 부탁드려요.
=> 어떤점을 확인해야 하는건가요? 구체적으로 말씀부탁드립니다.
=> 시간대별로 푸시 알림이 있어요. 이렇게 개발하셨겠지만, 다시 한 번 확인해달라는 요청입니다. QR챌린지의 달성률이 오전 8시에 온 경우가 있었어요. QR챌린지의 달성률 현황 푸시 메시지는 오전8시가 아니라, 오후 2시에 오는 것으로 되어 있습니다.
[GetWalk_App_Pop_ups_&_Notifications_171130.pptx](https://github.com/gracemj/getwalk/files/1750217/GetWalk_App_Pop_ups_._Notifications_171130.pptx)

**Comment by hannut91** [comment]
QR챌린지의 달성률이 오전 8시에 온 경우를 알려주세요

**Comment by Hyungseok-Seong** [comment]
제가 받은 푸시 메시지가 아니라서 캡쳐 화면은 없습니다. 그런 경우가 있었기에 확인 요청을 드리는 겁니다.
