### ISSUE TITLE
일본어 교정 - 챌린지에 참가하는 유저가 앙케이트 응모 후 챌린지 참가시 나타나는 얼럿

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#139]
- [x] 유저가 챌린지 참가시, 앙케이트가 있는 챌린지인 경우. 유저가 앙케이트에 응모하여 챌린지 참가시 나타나는 '챌린지에 참가합니다' 얼럿 메시지 변경해주세요. 마지막 구두점 (.)만 삭제해주시면 됩니다. -> チャレンジに参加する

![default](https://user-images.githubusercontent.com/34014924/36648662-a9deecb6-1ad9-11e8-9926-68347df50c32.jpg)

**Comment by hannut91** [comment]
- [ ] 유저가 챌린지 참가시, 앙케이트가 있는 챌린지인 경우. 유저가 앙케이트에 응모하여 챌린지 참가시 나타나는 '챌린지에 참가합니다' 얼럿 메시지 변경해주세요. 마지막 구두점 (.)만 삭제해주시면 됩니다. -> チャレンジに参加する
