### ISSUE TITLE
탈퇴 화면 스타일

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#14]
![image](https://user-images.githubusercontent.com/14939610/33251980-77ef169c-d37e-11e7-99cc-30bc95605e8e.png)

- [x] 상단 타이틀 스타일 확인부탁드립니다.

- [x] 폰트사이즈가 전체적으로 커보이는데 확인부탁드립니다.

- [x] 버튼 컬러와 확인체크 컬러가 조금 밝아 보입니다. 컬러값 확인부탁 드립니다.

![image](https://user-images.githubusercontent.com/14939610/33252041-ee06c5f0-d37e-11e7-8327-280db8e0259e.png)

- [x] 위의 이미지의 버튼색과 폰트색 확인부탁드립니다.

**Comment by applicatteam** [comment]
이슈가 없다면 닫아주세요
