### ISSUE TITLE
iPhone7, iOS 11.2.5에서 Walkthrough 화면 슬라이드 표시 문제

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#141]
- [ ] iPhone7, iOS 11.2.5에서 walkthrough 상황입니다. 다음 walkthrough 이미지를 보기 위해 화면에서 swipe하는 경우, 아래와 같이 walkthrough 이미지들이 중앙에 제대로 보이지 않고, 전/후 이미지가 반씩 걸쳐진 상태로 넘어가고 있습니다.

![iphone 7 ios 11 2 5](https://user-images.githubusercontent.com/34014924/36717056-ead55cb2-1bdf-11e8-9393-eb2994574390.jpg)
![spec](https://user-images.githubusercontent.com/34014924/36717061-ed0f5492-1bdf-11e8-9486-9de7bd70ce6c.jpg)

**Comment by applicatteam** [comment]
iphone6S+ / OS 11.2.5에서 아직 오류가 나고 있습니다.
* 한번 수정했었던 것인데 ipohne에서 앱을 실행할 때 window.width가 비정상적인 값을 가지고 있어서 생기는 문제입니다. 앱 실행 시 window.width를 출력해보면 이상한 값을 가지고 있는것을 확인할 수 있는데 이것을 고려해서 width를 100%를 했으나 왜 계속 안되는지는 확인하지 못해서 해결 하지 못했습니다.
![error](https://user-images.githubusercontent.com/15938046/37394399-02c2cd0e-27b7-11e8-8620-f11a71de1641.png)

**Comment by applicatdev** [comment]
수정 하였으며, 금요일 전달 드리는 버전으로 확인 해보실 수 있도록 하겠습니다. (+10.x.x버전 실행 오류 수정완료)

**Comment by Hyungseok-Seong** [comment]
180324 
해결된 이슈임을 확인했습니다.

![walkthrough](https://user-images.githubusercontent.com/34014924/37860651-36bb2ed6-2f6d-11e8-9fc2-666eedc6de66.jpg)
