### ISSUE TITLE
QR챌린지 QR코드 스캔시마다 프로그레스바가 시계 반대 방향으로 채워지고 있습니다.

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#142]
- [x] QR챌린지 QR코드 스캔시마다 프로그레스바의 시계 반대 방향으로 채워지고 있습니다. 시계 방향으로 프로그레스바가 진행되도록 변경해 주세요.

![qr counter clock wise](https://user-images.githubusercontent.com/34014924/36766778-b5dea09a-1c7a-11e8-9e51-666e0367dae8.jpg)

**Comment by hannut91** [comment]
- [ ] QR챌린지 QR코드 스캔시마다 프로그레스바의 시계 반대 방향으로 채워지고 있습니다. 시계 방향으로 프로그레스바가 진행되도록 변경해 주세요.

**Comment by Hyungseok-Seong** [comment]
- [ ] QR챌린지 QR코드 스캔시마다 프로그레스바의 시계 반대 방향으로 채워지고 있습니다. 시계 방향으로 프로그레스바가 진행되도록 변경해 주세요. (2018-02-28 19:36) 

![qr counter clock wise_2](https://user-images.githubusercontent.com/34014924/36783151-87f01cba-1cbe-11e8-903e-392fc886d22c.jpg)

**Comment by hannut91** [comment]
- [ ] 챌린지 종료 예정 푸시 메시지를 클릭하여 GetWalk app으로 들어오게 되면, HOME 화면이 표시되고 있습니다. 챌린지 종료 예정 푸시 메시지를 받은 유저가, 그 메시지를 클릭하여 들어오는 경우 HOME이 아닌, 마이챌린지-참가중챌린지-해당 챌린지의 상세 페이지로 이동하여야 합니다. 동시에, notification 영역에도 해당 알림을 클릭한 경우 동일한 페이지로 이동하여야 합니다. 현재는 둘 다 그렇게 되어 있지 않습니다.

**Comment by Hyungseok-Seong** [comment]
180307 15:12 문제 여전

![qr counterwise](https://user-images.githubusercontent.com/34014924/37076423-df2c37ba-2219-11e8-94b7-62b971298638.jpg)

**Comment by hannut91** [comment]
![screen shot 2018-03-08 at 11 39 10](https://user-images.githubusercontent.com/14071105/37130097-5fc2af20-22c5-11e8-93e0-7caf2148fd7e.png)
![screen shot 2018-03-08 at 11 39 16](https://user-images.githubusercontent.com/14071105/37130098-5fe81814-22c5-11e8-8474-e9eecaa65f29.png)

**Comment by Hyungseok-Seong** [comment]
iOS 10.3.3 에서 QR챌린지 QR코드 스캔시 프로그레스바가 반대 방향으로 올라가는 문제였습니다. 위에 첨부하신 이미지들은 iOS 버젼을 맞춰서 테스트 해보신 건가요 ? 타 iOS 버전에서는 동일한 문제가 발생하지 않았습니다.

**Comment by Hyungseok-Seong** [comment]
네

**Comment by Hyungseok-Seong** [comment]
앱에서 확인하신 건가요?
앱에서 확인하셨다면, 기종과 OS 버전 및 스크린샷을 함께 첨부해 주세요.

**Comment by applicatteam** [comment]
10.3.3 버전의 OS가 없어 확인해보지 못했으나,
Android 8.0.0(V30) /  iOS 11.2.5( iphone6S+) / 11.2.6 (iphone6)에서 정상 작동 됩니다.
1. Android 8.0.0 / V30 
![screenshot_2018-03-14-16-34-45](https://user-images.githubusercontent.com/15938046/37394607-86de3bb4-27b7-11e8-9b6d-2b0df4a844cd.png)
![screenshot_2018-03-14-16-34-50](https://user-images.githubusercontent.com/15938046/37394624-8d5894d0-27b7-11e8-843a-c68d89a4982a.png)

2. iphone6S+ (OS 11.2.5)
![kakaotalk_photo_2018-03-14-18-10-42_55](https://user-images.githubusercontent.com/15938046/37394743-d409dd44-27b7-11e8-9534-011b50a09f75.jpeg)
![kakaotalk_photo_2018-03-14-18-10-44_30](https://user-images.githubusercontent.com/15938046/37394750-d8083580-27b7-11e8-8305-cd0b902b012f.jpeg)

3. iphone6 (OS 11.2.6)
![img_0027](https://user-images.githubusercontent.com/15938046/37394771-ea98467c-27b7-11e8-947f-bd38377d1ff4.PNG)
![img_0028](https://user-images.githubusercontent.com/15938046/37394987-7d8e2bae-27b8-11e8-8d30-f43a322e6d2d.PNG)

**Comment by Hyungseok-Seong** [comment]
Smart Routine에서도 확인할 수 있도록 방법을 알려주시면 해당 OS 버전의 아이폰에서 확인 가능합니다.

**Comment by applicatteam** [comment]
확인해 보았으나 외부 iphone에서는 테스트 플라이트로 출시 전엔 확인이 불가능합니다.
이미 테스트 플라이트도 정식 서버와 연동되어있기 때문에
"테스트 서버"와 연동시키려면 iphone과 노트북을 직접 연결하여 설치해야합니다.

**Comment by Hyungseok-Seong** [comment]
테스트플라이트로 전달해주시면 해당 OS 버전에서 확인하겠습니다.

**Comment by Hyungseok-Seong** [comment]
테스트플라이트로 전달 받은 앱이, iPhone 5s, iOS 10.3.3에서는 열리지 않고 있습니다.
해당 이슈가 해결되었는지 확인할 수가 없습니다.

**Comment by Hyungseok-Seong** [comment]
180324 확인되었습니다.
