### ISSUE TITLE
QR챌린지 달성률 푸시 메시지가 유저의 달성 현황을 제대로 반영해서 보내주고 있지 않습니다

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#143]
- [ ] QR챌린지 달성률 푸시 메시지가 유저의 달성 현황을 제대로 반영해서 보내주고 있지 않습니다
![38_1](https://user-images.githubusercontent.com/34014924/36770967-d0d0f568-1c90-11e8-83da-b028d24bf06e.jpg)
![38_4](https://user-images.githubusercontent.com/34014924/36770968-d0f51010-1c90-11e8-9d82-2b79f51cc88a.jpg)

**Comment by hannut91** [comment]
- [ ] QR챌린지 달성률 푸시 메시지가 유저의 달성 현황을 제대로 반영해서 보내주고 있지 않습니다.
수정하였으나 현재시간 이전의 찍었던 QR은 적용되지 않고 새로 찍은 qrcode들은 이제 반영이되어 달성률을 표기합니다.

**Comment by Hyungseok-Seong** [comment]
수정하였으나 현재시간 이전의 찍었던 QR은 적용되지 않고 새로 찍은 qrcode들은 이제 반영이되어 달성률을 표기합니다.

무슨 뜻인지 이해하기가 어렵습니다.

**Comment by Hyungseok-Seong** [comment]
- [ ] QR챌린지 달성률 푸시 메시지가 유저의 달성 현황을 제대로 반영해서 보내주고 있지 않았습니다. QR챌린지 달성이 아니라, 스캔한 QR코드의 수 만큼 달성 현황이 표시되는 푸시 메시지를 테스트해서 전달해 주세요.

**Comment by applicatteam** [comment]
알겠습니다. 이 부분은 다시 확인 해보겠습니다.

**Comment by Hyungseok-Seong** [comment]
180320
이 이슈는 해결되지 않았습니다.
2시 발송 예정인 QR 챌린지 달성률 현황 푸시가 test 서버, 실서버 둘 다 발송되지 않았습니다.

**Comment by applicatdev** [comment]
확인항목으로 추가 하여 재 확인하겠습니다.

* arcade issue할 때 challengeParticipant의 아이디를 저장하지 않아서 생긴 문제로 수정하여서 전의 데이터가 아닌 최신버전으로 테스트할 시 이상이 없을것 으로 판단 되었으나, 재확인 필요 합니다.

**Comment by Hyungseok-Seong** [comment]
180324 
해결된 이슈임을 확인했습니다.

![qr](https://user-images.githubusercontent.com/34014924/37860624-9936faa0-2f6c-11e8-9e3e-db271535a21e.jpg)
