### ISSUE TITLE
결제 화면에서의 결제 금액과 Paypal에서의 결제 금액 불일치

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#145]
- [ ] 달성시 10엔의 상품을 90% 할인된 가격인 1엔으로 결제하여 얻는 챌린지입니다. 챌린지 결제 창에서 0엔으로 표시되고, paypal로 넘어가면 1엔의 계산 금액이 표시됩니다. 결제 금액이 paypal에서 결제할 금액과 동일하게 보이도록 수정 부탁드립니다.

![46-1](https://user-images.githubusercontent.com/34014924/36831390-edbf6bc0-1d6a-11e8-88a1-b899d38f251e.png)
![46-2](https://user-images.githubusercontent.com/34014924/36831391-ede57c7a-1d6a-11e8-8e68-55a131dede46.png)

**Comment by hannut91** [comment]
- [ ]  달성시 10엔의 상품을 90% 할인된 가격인 1엔으로 결제하여 얻는 챌린지입니다. 챌린지 결제 창에서 0엔으로 표시되고, paypal로 넘어가면 1엔의 계산 금액이 표시됩니다. 결제 금액이 paypal에서 결제할 금액과 동일하게 보이도록 수정 부탁드립니다.

**Comment by Hyungseok-Seong** [comment]
앱에서 확인하신 건가요?
앱에서 확인하셨다면, 기종과 OS 버전 및 스크린샷을 함께 첨부해 주세요.

**Comment by applicatteam** [comment]
소수점 계산 문제로 확인되어 수정 되었습니다.

1. 안드로이드 V30 / 8.0.0
![screenshot_2018-03-14-15-51-46](https://user-images.githubusercontent.com/15938046/37397588-50522fee-27bf-11e8-8ea7-7da91fde1c0a.png)
![screenshot_2018-03-14-16-40-15](https://user-images.githubusercontent.com/15938046/37397630-68f2f592-27bf-11e8-8203-fc6920cb9309.png)
![screenshot_2018-03-14-16-40-28](https://user-images.githubusercontent.com/15938046/37397635-6cd8e144-27bf-11e8-8ce7-0d38c6408045.png)

2. iphone6S+ / 11.2.5
![kakaotalk_photo_2018-03-14-18-10-45_49](https://user-images.githubusercontent.com/15938046/37397656-82536bd4-27bf-11e8-9cf0-8d377aeb860e.jpeg)
![kakaotalk_photo_2018-03-14-18-10-48_98](https://user-images.githubusercontent.com/15938046/37397661-85cfa4b2-27bf-11e8-8953-aa7eb329c944.jpeg)
![kakaotalk_photo_2018-03-14-18-10-50_55](https://user-images.githubusercontent.com/15938046/37397671-88c4ac1c-27bf-11e8-9458-75ebef21d930.jpeg)

3. iphone6 / 11.2.6
![img_0029](https://user-images.githubusercontent.com/15938046/37397710-9e9aed94-27bf-11e8-9e55-29117e6417e3.PNG)
![img_0032](https://user-images.githubusercontent.com/15938046/37397713-a277a8d0-27bf-11e8-8dd1-3d6f1541b4c3.PNG)
![img_0033](https://user-images.githubusercontent.com/15938046/37397718-a555a6a6-27bf-11e8-8f31-7132f527870c.PNG)

**Comment by Hyungseok-Seong** [comment]
- [ ] 결제 금액이 paypal에서 결제할 금액과 동일하게 보이도록 수정되었는지도 확인 요청드립니다.

**Comment by applicatteam** [comment]
이 버그는 앱상의 문제로 paypal에서는 %그대로 가격이 적용이 되었으나 앱단에서 소수점 처리가 안되어 정상으로 출력되지 않았던 부분입니다. paypal 화면도 찍어 드려야 하는 부분인가요? 이부분도 실 서버에서 만들어서 확인한 부분으로 아까 실데이터를 지워 지금은 화면 확인이 어렵습니다.

**Comment by Hyungseok-Seong** [comment]
네 필요합니당

**Comment by Hyungseok-Seong** [comment]
180320
Test 서버에서 확인되었습니다.

![payment_1](https://user-images.githubusercontent.com/34014924/37640793-813862d2-2c5a-11e8-83e5-2f1c60b8ea17.jpg)
![payment_2](https://user-images.githubusercontent.com/34014924/37640795-815f1116-2c5a-11e8-9ad8-81a2e7e01715.jpg)

**Comment by Hyungseok-Seong** [comment]
180328
해결되었습니다. close 하겠습니다.
