### ISSUE TITLE
챌린지 추첨 당첨자에게 푸시가 오지 않았습니다.

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#147]
- [ ] GetWalk ID thistokyo@gmail.com 이 [CBT] Test Dummy for Lottery 챌린지의 추첨 당첨이 되었습니다. 당첨자에게 제공되는 푸시 메시지가 가지 않았습니다. 확인 후 수정해주세요.

![lottery_winner_push](https://user-images.githubusercontent.com/34014924/36880947-d17b4e9e-1e0e-11e8-8825-4bf3e9a10cf7.jpg)

![lottery_winner](https://user-images.githubusercontent.com/34014924/36880934-b9f01b56-1e0e-11e8-9c42-0e102b70b673.PNG)

**Comment by hannut91** [comment]
- [ ] GetWalk ID thistokyo@gmail.com 이 [CBT] Test Dummy for Lottery 챌린지의 추첨 당첨이 되었습니다. 당첨자에게 제공되는 푸시 메시지가 가지 않았습니다. 확인 후 수정해주세요.
=> 푸시 메세지가 잘못되어있어서 메세지 내용을 수정하였습니다.

**Comment by Hyungseok-Seong** [comment]
다음 번 QA시 확인하겠습니다.

**Comment by applicatteam** [comment]
현재 코드 상 수정 완료되었습니다.
테스트 서버에서 lottery 부분 전체적으로 앱에서 확인 해보겠습니다. 

[Developer comment]
* Batch 에서 푸시메세지 텍스트가 잘못 들어가있어서 수정하였습니다. 
* 참고: twentyHandler.js 97줄

**Comment by Hyungseok-Seong** [comment]
180320
테스트 시나리오에 따라 테스트 필요함

**Comment by Hyungseok-Seong** [comment]
180328

확인되었습니다. close하겠습니다.

![180328_lottery_winner_noti](https://user-images.githubusercontent.com/34014924/38004470-64200a74-3277-11e8-817d-b232a64f2ce4.jpg)
