### ISSUE TITLE
QR챌린지 달성 후 상품 획득시 에러

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#149]
- [x] QR챌린지 달성후 상품수령 버튼을 눌러 나온 화면입니다. 당신이 가지고 있는 리워드가 아닙니다라는 안내입니다. 제대로라면 결제화면으로 이동해야 합니다. 

![qr](https://user-images.githubusercontent.com/34014924/36928912-c4a386fe-1ecd-11e8-92e3-098a443ef39b.png)

**Comment by hannut91** [comment]
내부 테스트 결과 이상이 없습니다. 안됐을 때 계정정보를 알려주시면 확인해보겠습니다.

**Comment by Hyungseok-Seong** [comment]
ID: sh@smart-routine.com
pw: getwalk2017

위 계정뿐만 아니라, 해당 CBT에서 달성했으나 상품 수령이 되지 않아 위 이미지 화면이 뜬 계정은 2개 더 있습니다.

xxxx5929@sina.cn
kc@smart-routine.com

**Comment by hannut91** [comment]
- [ ] QR챌린지 달성후 상품수령 버튼을 눌러 나온 화면입니다. 당신이 가지고 있는 리워드가 아닙니다라는 안내입니다. 제대로라면 결제화면으로 이동해야 합니다.

**Comment by Hyungseok-Seong** [comment]
앱에서 확인하신 건가요?
앱에서 확인하셨다면, 기종과 OS 버전 및 스크린샷을 함께 첨부해 주세요.

**Comment by applicatteam** [comment]
코드 수정 완료 / 테스트 서버에서 돌려본 뒤 스크린샷 첨부해 드리겠습니다.

[Developer comment]
* QRcode를 찍고나서 목표 QR코드를 다 찍었나 확인을 합니다. 근데 QRCodeIssued document가 만들어지기 전에 체크를해서 안됐었는데 수정하였습니다.
* 참고: QRcodeIssuedController.js 54줄

**Comment by Hyungseok-Seong** [comment]
180320 
테스트 서버에서 확인됨

![qr _](https://user-images.githubusercontent.com/34014924/37642557-dfbc5ba0-2c60-11e8-93cd-e1b5b39d73ec.jpg)

**Comment by Hyungseok-Seong** [comment]
180328
확인되었습니다. close하겠습니다.
![180328_qr _1](https://user-images.githubusercontent.com/34014924/38004647-2d308b96-3278-11e8-8eb2-01a96a25f5e1.jpg)
![Uploading 180328_qr 달성_2.jpg…]()
