### ISSUE TITLE
동일한 챌린지의 동일한 푸쉬 알람이 1-3분 시간차를 두고 3번 발송됐습니다.

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#150]
- [ ] 동일한 챌린지의 동일한 푸쉬 알람이 1-3분 시간차를 두고 3번 발송됐습니다.

![screenshot_20180302-200649](https://user-images.githubusercontent.com/34014924/36928920-dce644b8-1ecd-11e8-98a0-4a2b285f839f.png)

**Comment by hannut91** [comment]
- [ ] 동일한 챌린지의 동일한 푸쉬 알람이 1-3분 시간차를 두고 3번 발송됐습니다.

**Comment by Hyungseok-Seong** [comment]
- [ ] 동일한 챌린지의 동일한 푸쉬 알람이 1-3분 시간차를 두고 3번 발송됐습니다.

![default](https://user-images.githubusercontent.com/34014924/37134078-06c66b72-22da-11e8-9c40-1291bd01ac6d.jpg)
![2](https://user-images.githubusercontent.com/34014924/37134080-06eeb0fa-22da-11e8-851e-ca9ff4e2ba03.jpg)

**Comment by hannut91** [comment]
다시 수정했습니다.

**Comment by Hyungseok-Seong** [comment]
네 알겠습니다.
이는 앱 업데이트 없이도 확인 가능한 부분인가요? 그런 경우라면 내일 오후 2시에 올 푸시 알림 메시지로 QA 테스트 하겠습니다.

**Comment by hannut91** [comment]
네

**Comment by Hyungseok-Seong** [comment]
확인되었습니다.
