### ISSUE TITLE
마이챌린지-종료된챌린지에 유저가 참가한 챌린지가 표시되지 않음

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#152]
- [ ] 참가한 챌린지가 종료된 경우 유저의 마이챌린지-종료된챌린지에 리스트로 제공되어야 합니다.
현재 CBT에 참여한 유저들의 경우 마이챌린지-종료된챌린지에 리스트가 표시되지 않고 있습니다.

해당 계정은 아래와 같습니다.
ID: sh@smart-routine.com
PW: getwalk2017

이미지는 유저의 app 내 화면 및 admin에서 확인한 유저의 챌린지 참가 내역입니다.

![default](https://user-images.githubusercontent.com/34014924/36961436-b8c628e2-208e-11e8-9744-4488ed78bb24.jpg)
![default](https://user-images.githubusercontent.com/34014924/36961440-baa94ae0-208e-11e8-82f2-548af68a99e7.PNG)

**Comment by hannut91** [comment]
- [ ] 참가한 챌린지가 종료된 경우 유저의 마이챌린지-종료된챌린지에 리스트로 제공되어야 합니다.
현재 CBT에 참여한 유저들의 경우 마이챌린지-종료된챌린지에 리스트가 표시되지 않고 있습니다.

**Comment by applicatteam** [comment]
마이 챌린지 - 종료된 챌린지들 리스트 표시되고 있습니다.
[Developer comment]
* Find query에서 limit과 skip의 값이 잘못되어있어 수정하였습니다.
* 참고: my-challenge.ts 318줄

1. Android V30 / 8.0.0
![screenshot_2018-03-14-18-18-58](https://user-images.githubusercontent.com/15938046/37399429-02f5cafc-27c5-11e8-9438-e6a00819f289.png)

2. iphone6S+ / 11.2.5
![111](https://user-images.githubusercontent.com/15938046/37399461-17a9dc72-27c5-11e8-85fc-26c6381f2bf4.png)

3. iphone6 / 11.2.6
![image uploaded from ios 1](https://user-images.githubusercontent.com/15938046/37399488-2505127e-27c5-11e8-8a3b-adbc79fb4650.jpg)

**Comment by Hyungseok-Seong** [comment]
180320
테스트 서버에서 확인되었습니다.

**Comment by Hyungseok-Seong** [comment]
180324 iPhone 5s, iOS 10.3.3
참여 중인 챌린지가 있지만, 여러 번 새로 고침해도 마이챌린지에 반영되지 않습니다.
![default](https://user-images.githubusercontent.com/34014924/37860683-f4c57d96-2f6d-11e8-94e8-8627d7edc370.jpg)
