### ISSUE TITLE
마이챌린지-종료된챌린지: 챌린지 중복 표시

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#153]
- [ ] 유저가 참가한 하나의 챌린지가 중복해서 표시됩니다

![default](https://user-images.githubusercontent.com/34014924/36961492-faf05166-208e-11e8-9e42-2953f420d207.jpg)

**Comment by hannut91** [comment]
- [ ] 유저가 참가한 하나의 챌린지가 중복해서 표시됩니다

**Comment by applicatteam** [comment]
#152 번과 같은 맥락의 문제 였으며, 함께 해결 된 부분입니다.

**Comment by Hyungseok-Seong** [comment]
180320
테스트 서버에서 확인되었습니다.

**Comment by Hyungseok-Seong** [comment]
180328
확인했습니다. close하겠습니다.

![180328_mychalllenge_list_1](https://user-images.githubusercontent.com/34014924/38004782-c413cd20-3278-11e8-99ee-01d5be90da5f.jpg)
![180328_mychalllenge_list_2](https://user-images.githubusercontent.com/34014924/38004783-c43e12a6-3278-11e8-98dd-01f3b4d6272c.jpg)
