### ISSUE TITLE
앙케이트

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#154]
- [x] 앙케이트 선택지가 표시되지 않고 있습니다.
- [ ] 앙케이트의 질문이 긴 경우 스크롤이 되지 않아 선택지를 보거나, 클릭할 수 없습니다.

- [ ] 상단의 앙케이트 질문을 풀어 다음 질문으로 넘어갈때 표시되는 육각형 아이콘 컬러가 제대로 표시되지않습니다.각 질문의 단계에서 표시되어있어야합니다. 

![enquete no](https://user-images.githubusercontent.com/34014924/37074069-1fb12c48-220e-11e8-9670-b1e66f41d924.jpg)
![enquete](https://user-images.githubusercontent.com/34014924/37074073-230e4a1a-220e-11e8-8796-62c5b6e7ccd4.jpg)

**Comment by hannut91** [comment]
- [ ] 앙케이트 선택지가 표시되지 않고 있습니다.
- [ ] 앙케이트의 질문이 긴 경우 스크롤이 되지 않아 선택지를 보거나, 클릭할 수 없습니다.

**Comment by Hyungseok-Seong** [comment]
- [ ] 앙케이트 선택지 텍스트 가운데 정렬되고 있습니다. 본래 이렇게 스타일 지정이 가능하도록 개발하신건지 확인해주세요.

![default](https://user-images.githubusercontent.com/34014924/37078809-f4d9ccbc-2223-11e8-8a90-05859fca6ba3.png)

**Comment by hannut91** [comment]
![screen shot 2018-03-08 at 12 17 11](https://user-images.githubusercontent.com/14071105/37131208-aa0d5f30-22ca-11e8-9d4a-fea09a2b3030.png)
수정했습니다.

**Comment by Hyungseok-Seong** [comment]
차후 QA시 확인하겠습니다.

**Comment by applicatteam** [comment]
확인 완료. 수정 되었습니다.

1. 안드로이드 V30 / 8.0.0
![screenshot_2018-03-14-17-10-01](https://user-images.githubusercontent.com/15938046/37399614-7b1642a0-27c5-11e8-88ba-7376770a0436.png)
![screenshot_2018-03-14-17-11-02](https://user-images.githubusercontent.com/15938046/37399623-823d60c2-27c5-11e8-81b0-04bb9ba50c84.png)

2. iphone6S+ / 11.2.5
![kakaotalk_photo_2018-03-14-18-10-58_80](https://user-images.githubusercontent.com/15938046/37399654-9fe6af70-27c5-11e8-89b2-3260d7d201dd.jpeg)
![kakaotalk_photo_2018-03-14-18-11-00_36](https://user-images.githubusercontent.com/15938046/37399659-a426fbe4-27c5-11e8-8583-9a4dd020340a.jpeg)

3. iphone6 / 11.2.6
![img_0040](https://user-images.githubusercontent.com/15938046/37399694-c56bdb12-27c5-11e8-9e18-669b7bf487b3.PNG)
![img_0041](https://user-images.githubusercontent.com/15938046/37399696-c734e1aa-27c5-11e8-80e4-c6319317d33d.PNG)

**Comment by Hyungseok-Seong** [comment]
180320
#177 로 이관하겠습니다. 아래 이슈는 테스트 서버에서 확인되었습니다.
- [x] 앙케이트 선택지가 표시되지 않고 있습니다.
