### ISSUE TITLE
아이폰X 하단 컬러

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#155]
![image](https://user-images.githubusercontent.com/14939610/37079135-e24ea13e-2224-11e8-8072-8e6c22e41ee2.png)

- [ ] 하단 컬러값이 다른부분은 윗 부분과 동일한 색으로 연장해주세요

**Comment by hannut91** [comment]
![screen shot 2018-03-08 at 2 33 34](https://user-images.githubusercontent.com/14071105/37134883-e7075a0e-22dd-11e8-9057-f67d21c1bfd5.png)
- [ ] 하단 컬러값이 다른부분은 윗 부분과 동일한 색으로 연장해주세요

**Comment by applicatteam** [comment]
수정완료 / 한윤석 개발자분 핸드폰(iphoneX) 스크린샷 참조 부탁드립니다.
