### ISSUE TITLE
QR챌린지 상세화면 장소리스트 UI

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#156]
![image](https://user-images.githubusercontent.com/14939610/37079311-834e70b4-2225-11e8-8ec6-66dcbcffe653.png)

- [ ] 장소명이 길 경우 체크박스와의 사이가 너무 붙어있습니다. 1과 2의 여백은 왼쪽의 숫자와 텍스트의 여백과 동일하게해주세요.

**Comment by hannut91** [comment]
![screen shot 2018-03-08 at 2 49 44](https://user-images.githubusercontent.com/14071105/37135292-f9173668-22df-11e8-8b91-11c0e38d0ec8.png)
- [ ] 장소명이 길 경우 체크박스와의 사이가 너무 붙어있습니다. 1과 2의 여백은 왼쪽의 숫자와 텍스트의 여백과 동일하게해주세요.

**Comment by applicatteam** [comment]
수정완료.

1. 안드로이드 V30 / 8.0.0
![screenshot_2018-03-14-17-13-56](https://user-images.githubusercontent.com/15938046/37400152-54b13b4a-27c7-11e8-88b8-d1e04324f821.png)

2. iphone6S+ / 11.2.5
![kakaotalk_photo_2018-03-14-18-11-01_97](https://user-images.githubusercontent.com/15938046/37400174-647eb886-27c7-11e8-94b0-5a0153b9100f.jpeg)

3. iphone6 / 11.2.6
![img_0042](https://user-images.githubusercontent.com/15938046/37400191-7117a5e4-27c7-11e8-8c23-4acb0d5929b2.PNG)
