### ISSUE TITLE
admin 챌린지 참여 유저의 quiz num 데이터

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#157]
- [ ] admin에서 챌린지에 참여중인 유저의 데이터 중 quiz num의 데이터가 정확하지 않습니다. quiz num은 해당 챌린지의 퀴즈를 풀어서 보너스를 획득한 수치를 의미합니다.  cm@smart-routine.com thistokyo@gmail.com 두 계정이 퀴즈를 응모하여 보너스를 획득했지만 quiz num 값이 0인 상태입니다. 제대로 데이터값이 반영되고 있는지 확인 부탁드립니다.

![admin quiz](https://user-images.githubusercontent.com/34014924/37081429-c12d810c-222c-11e8-9b89-5c60b34aa02b.PNG)

**Comment by applicatteam** [comment]
수정 예정 / 데이터 확인 후 수정 진행 해야합니다.

**Comment by Hyungseok-Seong** [comment]
3/9 오후 3시에 slack으로 전달했던 admin/sponsor web에 대한 이슈 제기가 있었습니다. 해당 이슈에 대한 답변을 기다리고 있습니다. 확인 부탁드립니다.

**Comment by Hyungseok-Seong** [comment]
180320
#170 으로 이관합니다
