### ISSUE TITLE
추첨 시간 에러

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#158]
- [ ] 챌린지 추첨 기간으로 들어간 경우 그 다음날 오전 10시에 추첨 당첨자를 발표하는 것이 기획입니다.
현재는 10시간 뒤 추첨 당첨자가 발표되는 것으로 표시되고 있습니다. 본래의 기획대로 반영해 주세요.
![default](https://user-images.githubusercontent.com/34014924/37084953-3624694e-2237-11e8-848c-5bfd8f3be17a.png)

**Comment by applicatteam** [comment]
아직 수정 되지 않았습니다. 수정 진행 해야 합니다.
[Developer comment]
batch 변경해야하고 / client에서도 시간 관련 코드들을 봐야될 것 같습니다.
* 참고: home.ts 799줄

**Comment by applicatdev** [comment]
정상 종료된 챌린지는 종료날 다음날 오전 10시에 추첨 발표를 상품이 빨리 소진되어 조기 종료된 챌린지의 경우 종료된 시점의 다음날 오전 10시로 발표 되도록 수정 하겠습니다.

**Comment by Hyungseok-Seong** [comment]
180328
확인되었습니다. close하겠습니다.
![180328_lottery_noti](https://user-images.githubusercontent.com/34014924/38004884-4075c7a6-3279-11e8-84ce-aeb1d4eec6be.jpg)
