### ISSUE TITLE
유저가 참가중인 챌린지가 진행 중에서 -> 추첨 중으로 변경된 경우

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#159]
- [x] 유저가 참여 중인 개인 챌린지가 추첨에 들어가면 마이챌린지 걸음 수 카운트 영역에서 빠져나와야 합니다

![default](https://user-images.githubusercontent.com/34014924/37085386-44555ce8-2238-11e8-936c-8c99b96a327d.png)

**Comment by applicatteam** [comment]
수정 진행 해야하는 사항입니다.

[Developer comments]
*  batch에서는 챌린지의 상태가 변경되었을 떄 유저가 적립할 챌린지로 선택되어있으면 그것을 해제하도록 되어있는데 서버에서는 처리가 안되있어서 그런것으로 추측이 됩니다.
* 참고: getwalk-batch zeroHourHandler.js 251줄
* 참고: getwalk-server challengeController 484줄 챌린지를 업데이트 할 때 유저의 selectedChallengeParticipantId를 null로 바꿔줘야할 것 같습니다.

**Comment by applicatdev** [comment]
Developer comments 참고 하여 수정 완료 되었습니다.서버 단에서 처리를 안하고 있었으며, 처리되도록 수정 완료.
다음주 금요일 전달 파일에 포함.

**Comment by Hyungseok-Seong** [comment]
180328
확인되었습니다. close하겠습니다.
![180328_mychallenge_count_1](https://user-images.githubusercontent.com/34014924/38005046-076b8986-327a-11e8-81f1-e8e3b59d17e3.jpg)
![180328_mychallenge_count_2](https://user-images.githubusercontent.com/34014924/38005047-0792d324-327a-11e8-90ae-2051adde1f48.jpg)
![180328_mychallenge_count_3](https://user-images.githubusercontent.com/34014924/38005048-07d5fc94-327a-11e8-8098-cb87f9a6dde5.jpg)
