### ISSUE TITLE
마이페이지 화면 스타일

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#16]
![image](https://user-images.githubusercontent.com/14939610/33252628-a05c7a1c-d382-11e7-8dbf-b04656badb43.png)

- [x] 프로필 이미지 외곽에 알수없는 회색선들이...뭘까요?

- [x] 레벨과 누적걸음 수의 폰트컬러 확인부탁드립니다.

- [x] 상단 숫자폰트의 두께와 크기 확인부탁드립니다.

- [x] k는 K대문자로 바꿔주세요

- [x] 메뉴 탭 전환 시 텍스트 위치가 올라갑니다. 텍스트는 고정되어있어야합니다. 아래 컬러바와 폰트컬러만 바뀝니다.

- [x] 리스트의 폰트 크기가 커보입니다. 확인부탁드립니다.

![image](https://user-images.githubusercontent.com/14939610/33253224-c21cbd44-d385-11e7-8ed2-eadfcb5d0eb4.png)

- [x] 결제내역의 폰트 컬러 확인부탁드립니다

**Comment by gracemj** [comment]
![image](https://user-images.githubusercontent.com/14939610/34710212-bc350e1e-f55d-11e7-83ab-1bdb1f208bbd.png)

- [ ] 현재 보여지는 화면입니다. 깨진부분들 확인해주세요

**Comment by applicatteam** [comment]
이슈가 없다면 닫아주세요
