### ISSUE TITLE
QR챌린지 달성시 버튼 문구 교정

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#161]
- [ ] 유저가 QR챌린지 달성시 홈 화면과 챌린지 상세 화면에서의 버튼 문구가 서로 다르게 표시되고 있습니다.  홈 화면과 챌린지 상세 화면의 버튼 안의 텍스트를 商品受取 로 통일해 주세요.

![qr _1](https://user-images.githubusercontent.com/34014924/37128736-cf4895b4-22be-11e8-8e3a-e74c247e4b77.jpg)
![qr _2](https://user-images.githubusercontent.com/34014924/37128737-cf74dff2-22be-11e8-8d90-c16a33f42e91.jpg)

**Comment by applicatteam** [comment]
수정해야합니다.
[Developer comments]
 QR달 성 시, 홈 화면과 챌린지 상세 화면에서의 버튼 문구 텍스트를 " 商品受取 " 로 통일 시켜주세요.

**Comment by Hyungseok-Seong** [comment]
180320
#182 이슈로 이관합니다.

**Comment by applicatdev** [comment]
수정 완료 하였습니다.
