### ISSUE TITLE
앱 화면이 하얗게 표시되며,  앱이 정상 작동하지 않음

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#163]
- [ ] 앱을 다시 켤 때, 화면이 바로 표시되지 않고, 2번째 이미지처럼 하얗게 표시만 되고 app 내 화면이 표시되지 않는 경우가 종종 있습니다.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34014924/37141692-2ff928bc-22f9-11e8-876e-823b61b48b90.gif)

**Comment by applicatteam** [comment]
혹시 이부분도 10.3.3 버전에서의 문제였었나요?

[Developer comments]
* 현재 내부 테스팅폰에서는 버그 케이스를 확인해 보지 못했는데 버전 받아 확인 해봐야할것같습니다.

**Comment by Hyungseok-Seong** [comment]
버젼 문제는 아니었습니다. 해당 문제가 발생했던 기종과 OS는 다음과 같습니다.
iPhone7, iOS 11.2.5

**Comment by Hyungseok-Seong** [comment]
180320
현재 테스트 버전에서 iPhone 5S, 10.3.3 에서는 최초 앱 구동시에도 정상 동작하지 않습니다.

**Comment by applicatdev** [comment]
해당 부분은 walkthrough부분을 수정하면서 수정 하였습니다. 10.x.x 대 정상 동작 부분도 수정 하였으며, 금요일 전달 드릴 파일에서 한번 확인 부탁드립니다.

**Comment by Hyungseok-Seong** [comment]
180328
이 이슈가 재현되지 않았습니다.
차후 릴리즈시 발현되면 문제에 대해 다시 리포트 드리겠습니다.
우선 close하겠습니다.
