### ISSUE TITLE
Admin web - 챌린지 참여 유저들 데이터

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#164]
- [ ] Admin web에서 챌린지 참여 유저들의 데이터 값이 제대로 반영되고 있지 않습니다. 첨부한 화면은 QR챌린지의 유저 현황입니다. 유저 한 명을 제외하고 QR코드 스캔 달성률이 모두 0으로 표시되고 있습니다. 내부 QA 기간 동안 10개의 QR코드 중 6-8개를 스캔했습니다. 확인해 주세요.

![admin](https://user-images.githubusercontent.com/34014924/37192245-cd72a0e2-23a7-11e8-8aa3-490d63bd850f.PNG)

**Comment by applicatteam** [comment]
#143  이슈랑 연관이 있을 것 같습니다. 확인 부탁드립니다.

**Comment by Hyungseok-Seong** [comment]
180320
#170 으로 이관합니다
