### ISSUE TITLE
유저가 참가 중인 챌린지가 홈에는 표시되지만, 마이챌린지에는 표시되지 않음

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#165]
- [ ] 유저가 참가 중인 챌린지가 홈에는 표시되지만, 마이챌린지-참가중 챌린지에는 표시되지 않고 있습니다. 확인해 주세요.

GetWalk ID: sh@smart-routine.com
iPhone 5s, iOS 10.3.3

![_1](https://user-images.githubusercontent.com/34014924/37195226-40cec28e-23b5-11e8-94e3-8c871613e1c2.jpg)
![_2](https://user-images.githubusercontent.com/34014924/37195229-42a5fad2-23b5-11e8-898e-c72a1e8c9247.jpg)

**Comment by applicatteam** [comment]
#152 번과 같은 문제로 발생한 부분으로 중복 이슈 입니다. 해결되었습니다.

**Comment by Hyungseok-Seong** [comment]
180324 iPhone 5s, iOS 10.3.3
참여 중인 챌린지가 있지만, 여러 번 새로 고침해도 마이챌린지에 반영되지 않습니다. #152 가 이쪽으로 이관되었습니다.
![default](https://user-images.githubusercontent.com/34014924/37860683-f4c57d96-2f6d-11e8-94e8-8627d7edc370.jpg)

**Comment by Hyungseok-Seong** [comment]
180328
확인되었습니다. close하겠습니다.
