### ISSUE TITLE
챌린지 결제 타이머 기간 텍스트 표시

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#166]
- [ ] 챌린지 결제 타임인 경우 홈과 마이챌린지-상세 페이지에서는 결제 시간 위 text가 '결제타이머'인 決済タイム 으로 표시되어야 합니다. 마이챌린지-상세 페이지에서 표시된 決済時間을 決済タイム 으로 변경해주세요.
![_](https://user-images.githubusercontent.com/34014924/37402095-9ee23c72-27cd-11e8-851e-d5f038b8d15f.jpg)
![_](https://user-images.githubusercontent.com/34014924/37402096-9f0a9802-27cd-11e8-8dcc-b9f1943fc82b.jpg)

**Comment by applicatteam** [comment]
텍스트 수정 진행 해야합니다. 확인 부탁드립니다.
[Developer comments]
마이챌린지 > 상세 페이지에서 표시된 
" 決済時間 "을 " 決済タイム " 으로 변경.

**Comment by Hyungseok-Seong** [comment]
180324
#182 로 이관하겠습니다.
