### ISSUE TITLE
 一時的な問題が発生しました 라는 얼럿이 뜨는 경우

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#168]
- [ ] GetWalk app 내에서 아래와 같은 얼럿 메시지가 뜨는 경우가 언제인가요? 문제 상황이 발생하는 조건과 개발사의 대응 방안, 운영에서 준비해야 할 사항은 어떤 것이 있는지 구체적인 설명을 부탁드립니다.

![image uploaded from ios](https://user-images.githubusercontent.com/34014924/37449253-f1c2e884-286c-11e8-84cc-884c40cd6998.png)

**Comment by applicatdev** [comment]
서버에서 접속이 안되거나 받아들일수 없는 변수로 요청 하였을때 나오는 팝업입니다.
유저의 사용 환경(인터넷 환경) 등에 따라서도 나올 수 있는 부분으로
어떤 상황에서 해당 팝업이 발생하였는지는 사용자에게 확인을 받아야합니다.
해당 팝업이 뜨는 상황이 버그라고 인식된다면 개발사(어플리캣)에 전달 주시면 확인하여 수정 진행합니다.

**Comment by Hyungseok-Seong** [comment]
180324
안드로이드(폰 정보 차후 전달)에서, 회원 가입 단계에서 모든 사항 입력 후 다음으로 넘어가지 않는 경우 발생

![default](https://user-images.githubusercontent.com/34014924/37860776-e0fcca92-2f6f-11e8-9d69-ea7a48048097.png)

**Comment by Hyungseok-Seong** [comment]
180328
바로 위의 이슈는 안드로이드 APK 문제였음을 전달받았습니다.
최초 이슈에 대한 답변으로 갈음하여, 이슈를 close하겠습니다.
