### ISSUE TITLE
홈> 추첨진행 화면 스타일

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#17]
![image](https://user-images.githubusercontent.com/14939610/33253363-64a0d4a6-d386-11e7-836e-3c77ffcfdc43.png)

- [x] 배경색 확인부탁드립니다.

- [x] 박스 안 요소들 간의 여백과 간격을 확인해주세요

**Comment by gracemj** [comment]
![image](https://user-images.githubusercontent.com/14939610/33253363-64a0d4a6-d386-11e7-836e-3c77ffcfdc43.png)

- [ ] 배경색 확인부탁드립니다.

- [ ] 박스 안 요소들 간의 여백과 간격을 확인해주세요

**Comment by applicatteam** [comment]
이슈가 없다면 닫아주세요
