### ISSUE TITLE
[admin] challenge-reward 에서 이미지 업로드시

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#173]
- [x] [Test_admin] challenge-reward 에서 이미지 업로드시, reward 1장, main challenge 1장, sub challenge 10장으로 업로드 되어야 합니다. 현재 sub challenge의 경우 최대 8장까지만 업로드 되는 형태로 되어 있습니다. 10장까지 올릴 수 있도록 변경해 주세요.

![admin-reward](https://user-images.githubusercontent.com/34014924/37632332-0dafe34a-2c31-11e8-92a1-044f2f8c4b78.PNG)

**Comment by Hyungseok-Seong** [comment]
- [ ] Test admin 뿐만 아니라, 실서버 admin도 동일한 문제가 발생하고 있습니다. 확인해 주세요.

**Comment by Hyungseok-Seong** [comment]
180324
Test server 수정 확인되었습니다.

**Comment by applicatdev** [comment]
네 감사합니다.

**Comment by Hyungseok-Seong** [comment]
180328
- [ ] 테스트 서버는 수정되었습니다.
- [ ] 실서버 admin은 아직 수정되지 않았습니다. 실서버 admin 적용되면 close하겠습니다.

![test-admin reward](https://user-images.githubusercontent.com/34014924/38005843-89e43a36-327d-11e8-9e64-7852afac98bb.PNG)
![real-admin reward](https://user-images.githubusercontent.com/34014924/38005845-8a07bd6c-327d-11e8-96e8-c77c7ac71357.PNG)

**Comment by applicatdev** [comment]
테스트 서버에서 관리자에서 수정되는 모든 사항들은 최종 확인 후 실서버 관리자 페이지에 최종 적용 하겠습니다 :)

**Comment by Hyungseok-Seong** [comment]
네 알겠습니다 :)
admin, sponsor는 우선 테스트 서버 기준으로 깃헙 이슈 open/close처리하겠습니다.

이 이슈는 close하겠습니다~
