### ISSUE TITLE
챌린지 상세 페이지의 아이콘 크기가 서로 다름

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#174]
- [ ] 챌린지에서 챌린지의 상세 페이지에 들어간 경우 및 마이챌린지에서 챌린지의 상세 페이지로 들어간 경우, type과 class의 아이콘 크기가 달라지고 있습니다. 디자인 가이드대로 통일해주세요. 위: 챌린지-상세 / 아래: 마이챌린지-상세

![-](https://user-images.githubusercontent.com/34014924/37632419-76342afc-2c31-11e8-8bfa-50072ecd7b45.jpg)
![-](https://user-images.githubusercontent.com/34014924/37632420-77627cc6-2c31-11e8-98e6-1b731738286e.jpg)

**Comment by applicatdev** [comment]
확인 하였습니다. 해당 페이지는 "같은 코드로 개발된 같은 페이지"로 들어갑니다.
아이콘 사이즈 다른 부분이 없습니다.

**Comment by Hyungseok-Seong** [comment]
180324
이 문제는 지금까지의 개발단계에서 전혀 문제로 발생하지 않았습니다만, 이번 테스트 서버에서 따로 전달 주신 뒤 부터 발생하고 있습니다. 확인 후 수정 부탁드립니다.

![-](https://user-images.githubusercontent.com/34014924/37860827-ea2ef120-2f70-11e8-9d2d-41be32fcc8a4.jpg)
![- -](https://user-images.githubusercontent.com/34014924/37860828-ebc2db50-2f70-11e8-8a4f-deff4d2be883.jpg)
![-](https://user-images.githubusercontent.com/34014924/37860829-ed403144-2f70-11e8-893c-020bb7726dcf.jpg)

**Comment by applicatdev** [comment]
180327_재확인 부탁드립니다. 테스트 폰에서 해당 현상이 확인 되지 않습니다ㅠ
Android 갤럭시 S7 
![screenshot_20180327-134401](https://user-images.githubusercontent.com/37545654/37947669-5ab6dc7a-31c7-11e8-9616-126b2ccaf483.png)
![screenshot_20180327-134544](https://user-images.githubusercontent.com/37545654/37947670-5adad13e-31c7-11e8-937f-fdd4fa524ccf.png)

iphone6
![image uploaded from ios 2](https://user-images.githubusercontent.com/37545654/37947694-6d16b3d6-31c7-11e8-88b5-5fc6297ebf3d.png)
![image uploaded from ios 3](https://user-images.githubusercontent.com/37545654/37947695-6d3ea8be-31c7-11e8-84dd-94a7ca99891e.png)

**Comment by Hyungseok-Seong** [comment]
챌린지 참가 전/후에 상세 페이지에서 다르게 표시되는 경우입니다. 
1) 챌린지-상세페이지
2) 마이챌린지-상세페이지
이 1), 2)의 경우에 따라 아이콘의 크기가 달라지는 문제였습니다.

**Comment by applicatdev** [comment]
네 이해했습니다.
금일 첨부해드린 화면이미지가 순차적으로 각 기종에서 1. 챌린지 - 상세페이지 / 2. 마이챌린지 - 상세페이지 화면 스크린샷입니다. 
또한 코드상으로도 같은 소스로 짜인 같은 화면으로 들어가는 페이지라 다르게 출력 되지 않는 화면 입니다.
이부분은 현재 버전으로 다시 확인 한번 부탁드리겠습니다.

**Comment by Hyungseok-Seong** [comment]
방금 확인했습니다.
iPhone7, iOS 11.2.6 입니다. 이 모델뿐 아니라, Smart Routine에서 확인 시 계속 동일한 문제가 나타납니다.

![default](https://user-images.githubusercontent.com/34014924/37949753-e35a1282-31d0-11e8-9d74-b74a8caf140e.jpg)
![default](https://user-images.githubusercontent.com/34014924/37949755-e49feed2-31d0-11e8-830a-21b2bea0183f.jpg)

**Comment by applicatdev** [comment]
다시 확인하여 수정 완료 했습니다.

**Comment by Hyungseok-Seong** [comment]
180328

아직 미해결된 상황으로 보입니다.

![180328_](https://user-images.githubusercontent.com/34014924/38002794-3b7937d8-326f-11e8-9ecd-222a21db6b40.jpg)
![180328_](https://user-images.githubusercontent.com/34014924/38002795-3b9ff170-326f-11e8-8af7-988888799408.jpg)

**Comment by Hyungseok-Seong** [comment]
#197 으로 이관하고 이 이슈는 close하겠습니다.
