### ISSUE TITLE
개인챌린지-퀴즈가 뜨지 않음

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#175]
- [x] admin에서 입력한 퀴즈가 app에서 나타나지 않고 있습니다.
![quiz](https://user-images.githubusercontent.com/34014924/37632469-a807a004-2c31-11e8-8b0b-cf7d57eb9923.jpg)

**Comment by applicatdev** [comment]
"기존 데이터 마이그레이션 하면서 data 연결이 제대로 안된 부분으로 사료 됩니다.
새로운 챌린지에서 혹시 동일한 문제가 일어 난다면 챌린지 제목을 알려주세요."

**Comment by Hyungseok-Seong** [comment]
180324
테스트 진행하면서 확인하겠습니다.

**Comment by applicatdev** [comment]
180327
퀴즈 참여하기 이상 없이 참여 되고 있습니다. 테스팅 화면 첨부 드립니다. (iPhone6 / 11.2.6) 
![image uploaded from ios 2](https://user-images.githubusercontent.com/37545654/37949658-7e671cda-31d0-11e8-8e45-0d2b84289c69.png)
![image uploaded from ios 3](https://user-images.githubusercontent.com/37545654/37949663-83682134-31d0-11e8-8e28-14b3cf4c3b41.png)
![image uploaded from ios 4](https://user-images.githubusercontent.com/37545654/37949670-894d0e02-31d0-11e8-8d0f-6683b640ebf5.png)
![image uploaded from ios 5](https://user-images.githubusercontent.com/37545654/37949671-8dfabf94-31d0-11e8-8553-372b1ca6153a.png)
![image uploaded from ios 6](https://user-images.githubusercontent.com/37545654/37949676-9154d53a-31d0-11e8-8661-6aad9855fbb7.png)

**Comment by Hyungseok-Seong** [comment]
180327 
테스트 시나리오에 따라 수정된 부분 확인되었습니다.
이슈 닫겠습니다.
