### ISSUE TITLE
앙케이트부분

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#177]
![image](https://user-images.githubusercontent.com/14939610/37632541-036a6bd4-2c32-11e8-9d95-bdc948b8455e.png)

- [ ] 앙케이트는 순차적으로 해결하지 않으면 다음 문제로 넘어가지 못합니다. 현재는 첫번째 문제를 풀다가도 문제의 순서에 상관없이 문제를 풀 수 있도록 되어있습니다.

- [ ] 문제가 길어질 경우 영역에서 잘려버리는데요. 이부분은 해결이 불가능한가요?

**Comment by applicatdev** [comment]
문제의경우, 문제를 전부 풀지 않으면 제출이 불가능 하도록 되어있습니다. 그래도 문제를 순차적으로 해결하게 해야하는 것인가요? 유저는 문제들을 전부 왔다갔다 확인하며 선택지를 선택하며 최종 다풀고 제출이 되는 프로세스가 좋을 것 같은데,확인 부탁드립니다. 스크롤 기능은 적용 하였습니다.

**Comment by gracemj** [comment]
네, 순차적으로 풀어야 다음으로 넘어갈 수 있게해주시고, 이전에 풀었던 문제는 다시 볼 수 있게 해주시면됩니다.

**Comment by applicatdev** [comment]
순차적으로 작업을 하게 하는것에 대해선 이슈가 있습니다. 문제를 순차적으로 풀되 이전 문제를 다시 볼수있게 보게 하는것이 불가능 합니다. 순차적으로 보게하려면 '스와이프'기능을 제거 해야하는데 그렇게 되면 현재의 페이지를 넘기는 방식을 다른 방식으로 변경해야 합니다. 확인 부탁드립니다.

**Comment by Hyungseok-Seong** [comment]
앙케이트 문제 풀이 순서를 순차적으로 진행하지 않고, 현재 이슈가 해결된 상태 및 스크롤 기능이 적용된 개발 상태로 해 주시면 됩니다.

**Comment by applicatdev** [comment]
네 감사합니다 Close 부탁드립니다

**Comment by Hyungseok-Seong** [comment]
180324

앙케이트 답안 선택시 다중 선택되는 문제가 Android에서 나타났습니다. 수요일에 전달주실 때 다시 확인하고, 문제 없으면 이 이슈를 close하겠습니다.

![default](https://user-images.githubusercontent.com/34014924/37952038-7a13c6e8-31d9-11e8-90b4-7f8868e174ba.jpg)

**Comment by applicatdev** [comment]
180326일 전달 드린 1.0.38 버전 파일에서 해당 문제 발생이 안되고 있습니다.

**Comment by Hyungseok-Seong** [comment]
180328
확인되었습니다. close하겠습니다.
