### ISSUE TITLE
진행바 스타일

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#18]
![image](https://user-images.githubusercontent.com/14939610/33253965-b6abf9f8-d389-11e7-864a-25be36caed26.png)

- [ ] 빨간 삼각표시 지점과 QR챌린지의 지점 개수 분할 외에는 자연스럽게 연결되는 바 스타일입니다.

**Comment by applicatteam** [comment]
![image](https://user-images.githubusercontent.com/15938046/35210603-3dd98d9a-ff96-11e7-9f37-f68e5ccad37f.png)
