### ISSUE TITLE
마이리워드: 상품 수령기간과 수령 가능 tag 불일치 문제

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#184]
- [ ] 마이리워드에서 받은 상품이 아직 수령 기간 내에 있지만, 期間満了(기간 만료) 된 상품으로 tag가 붙어 있습니다. 확인 후 수정해주세요.

![default](https://user-images.githubusercontent.com/34014924/37642579-016bc736-2c61-11e8-9787-83cc022543ee.jpg)

**Comment by applicatdev** [comment]
버그 fix 적용후 만들어진 새로운 챌린지에서만 적용 됩니다. (이전데이터에는 적용 되지 않습니다.)

**Comment by Hyungseok-Seong** [comment]
180328

확인되었습니다. close하겠습니다.
![180328_myreward](https://user-images.githubusercontent.com/34014924/38009810-26bf9fe0-3291-11e8-8b03-bf8ff51f8b34.jpg)
