### ISSUE TITLE
홈 화면 다이아몬드 클라스 텍스트 표기에 줄바꿈

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#188]
- [ ] 홈 화면 다이아몬드 클라스 텍스트 표기에 줄바꿈이 들어가 있습니다. 줄 바꿈이 되지 않도록 변경해 주세요. (기종, OS 버전 무관하게 공통으로 나타나는 문제입니다)

![default](https://user-images.githubusercontent.com/34014924/37860941-2668137c-2f73-11e8-8844-35b78a0586a9.jpg)

**Comment by applicatdev** [comment]
수정 완료 하였습니다.

**Comment by Hyungseok-Seong** [comment]
180328
iPhone 5S, iOS 10.3.3에서 문제 아직 남아 있습니다.
(iPhone 7에서는 문제 없습니다)

![iphone 5s ios10 3 3 home](https://user-images.githubusercontent.com/34014924/38002718-d9dcaf96-326e-11e8-96d2-4a3da0f5c7b8.jpg)

**Comment by Hyungseok-Seong** [comment]
180328
#192 이슈로 이관하겠습니다. close하겠습니다.
