### ISSUE TITLE
상단 UI 스타일

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#2]
![image](https://user-images.githubusercontent.com/14939610/33246797-5b3fddaa-d35c-11e7-8c23-74355cf22783.png)

- [x] 햄버거 버튼의 크기와 위치, 칼라 확인부탁드립니다.

- [x] 알림아이콘 디자인이 다릅니다. 

- [x] 알림아이콘의 New 뱃지가 달린화면도 보고싶습니다.

- [x] 상단 타이틀의 폰트 굵기가 두껍습니다. 기존 디자인 확인부탁드립니다.

- [x] 최상단의 toolbar의 색은 화이트로 적용이 안되나요?

**Comment by gracemj** [comment]
@applicatteam 👍

**Comment by applicatteam** [comment]
이슈가 없다면 닫아주세요

**Comment by gracemj** [comment]
- [ ] 챌린지 상세페이지의 제목은 여전히 두껍습니다. 상단의 제목, 챌린지명은 동인한 스타일입니다

**Comment by applicatteam** [comment]
![image](https://user-images.githubusercontent.com/15938046/35089156-6e87b540-fc79-11e7-85ab-66f6793779d0.png)
