### ISSUE TITLE
intro, login, join, 더 보기 메뉴, 마이페이지

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#25]
- [x] 회원가입 후 전화 걸기 권한 요청 (위치 정보 권한 요청이 먼저 시작되는 것이 기획입니다)
- [x] 마이 페이지 결제 내역 클릭 시 [myreward_detail] 로 이동해야 함
- [x] join 에서 term of use와 privacy policy를 새로 전달드렸는데, 아직 반영되지 않았습니다. 확인 부탁드립니다.
- [x] 공지사항: 새로운 공지사항이 추가되어도 N (NEW) 표시가 나타나지 않습니다.

**Comment by Hyungseok-Seong** [comment]
- [ ] 회원 가입 단계에서 비밀번호 설정 시 6글자 이상으로 가이드가 나와있지만, 실제로 가입시 7글자 여야 가입이 가능합니다. 확인해 주세요.

**Comment by Hyungseok-Seong** [comment]
- [ ] 알림 하위 하나 선택 시 '전체 알림 설정'도 함께 설정됩니다

![image_4ea044e](https://user-images.githubusercontent.com/34014924/34026169-89addbb2-e197-11e7-823f-3fcf468a8d57.jpg)

**Comment by Hyungseok-Seong** [comment]
![findpw](https://user-images.githubusercontent.com/34014924/34472312-75c30fdc-efa2-11e7-87e8-6786f762285f.jpg)

- [ ] '確認' 버튼은 이메일에만 있습니다. 
- [ ] '確認' 글자가 줄바꿈되어 글자가 잘려 보입니다.

**Comment by Hyungseok-Seong** [comment]
- [ ] join 에서 term of use와 privacy policy를 새로 전달드렸는데, 아직 반영되지 않았습니다. 확인 부탁드립니다.

**Comment by Hyungseok-Seong** [comment]
![default](https://user-images.githubusercontent.com/34014924/34546240-e6d5bcda-f135-11e7-8a7f-d4714e779538.jpg)

- 유저 정보(성별, 출생년도, 거주지) 입력 후 마이페이지에서 성별 표시가 나타나지 않습니다.

**Comment by Hyungseok-Seong** [comment]
- 공지사항: 새로운 공지사항이 추가되어도 N (NEW) 표시가 나타나지 않습니다.

**Comment by applicatteam** [comment]
- [ ] 회원가입 후 전화 걸기 권한 요청 (위치 정보 권한 요청이 먼저 시작되는 것이 기획입니다)
- [ ] 마이 페이지 결제 내역 클릭 시 [myreward_detail] 로 이동해야 함
- [ ] join 에서 term of use와 privacy policy를 새로 전달드렸는데, 아직 반영되지 않았습니다. 확인 부탁드립니다.
- [ ] 공지사항: 새로운 공지사항이 추가되어도 N (NEW) 표시가 나타나지 않습니다.

**Comment by Hyungseok-Seong** [comment]
- 공지사항: 새로운 공지사항이 추가되어도 N (NEW) 표시가 나타나지 않습니다.
확인되었습니다.

![1](https://user-images.githubusercontent.com/34014924/35307761-ba000370-00e7-11e8-866c-8ec322b9b4bc.jpg)
![2](https://user-images.githubusercontent.com/34014924/35307762-ba404b4c-00e7-11e8-8548-3107144f51c2.jpg)

**Comment by Hyungseok-Seong** [comment]
- 마이 페이지 결제 내역 클릭 시 [myreward_detail] 로 이동해야 함
![1](https://user-images.githubusercontent.com/34014924/35307861-589a9a40-00e8-11e8-8b9d-a6dda8422f15.jpg)
![2](https://user-images.githubusercontent.com/34014924/35307862-58c26f2a-00e8-11e8-83f7-981fb8d0eb03.jpg)
