### ISSUE TITLE
챌린지 리스트, 상세 페이지

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#26]
- [x] qr 챌린지의 맵 확대 안 됨
- [ ] (171215 추가) qr 챌린지 상세 페이지에서 돋보기 버튼 클릭 시 맵 화면이 꽉 차야 함. google map처럼 맵 확대 및 더 보기
- [ ] 챌린지 참가시 나오는 얼럿에 '확인' 한국어가 들어가 있습니다.

**Comment by Hyungseok-Seong** [comment]
오늘 날짜로 추가된 사항 및 체크된 항목 중 기능이 작동하지 않는 부분 확인 부탁드립니다.

**Comment by Hyungseok-Seong** [comment]
- [ ] 앙케이트: 하나 선택 시 모든 게 선택되는 이슈

![image_99c5dec](https://user-images.githubusercontent.com/34014924/34026150-6a24ffe6-e197-11e7-8463-7e25e833a697.jpg)

**Comment by Hyungseok-Seong** [comment]
![district](https://user-images.githubusercontent.com/34014924/34472493-09f96b52-efa7-11e7-8128-eb06da536a3f.jpg)

- [ ] admin에서 입력한 지역명으로 반영되지 않고 있습니다.

**Comment by Hyungseok-Seong** [comment]
- [ ] 추천 챌린지 클릭이 안 되고 있습니다.

**Comment by Hyungseok-Seong** [comment]
- 챌린지 참가시 나오는 얼럿에 '확인' 한국어가 들어가 있습니다. 

![default](https://user-images.githubusercontent.com/34014924/34555197-d61046f2-f173-11e7-8d44-2554fc41773c.jpg)

**Comment by applicatteam** [comment]
- [ ] qr 챌린지의 맵 확대 안 됨
- [ ] (171215 추가) qr 챌린지 상세 페이지에서 돋보기 버튼 클릭 시 맵 화면이 꽉 차야 함. google map처럼 맵 확대 및 더 보기
- [ ] 챌린지 참가시 나오는 얼럿에 '확인' 한국어가 들어가 있습니다.
