### ISSUE TITLE
마이챌린지, 마이챌린지 상세

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#27]
- [x] 챌린지 참여하지 않은 경우, 챌린지에 참여하고 있어도 걸음 수를 적립할 수 없는 경우 안내 멘트가 달라야 함 확인 요망
- [x] 챌린지 카운트 버튼이 적용되는 챌린지/적용되지 않는 챌린지가 확실하게 정해져 있는데 반영되지 않았음
- [x] 챌린지 타임라인에 따른 화면 및 안내 멘트가 기획과 다릅니다. 챌린지 시작 전 / 진행 / 결제 / 추첨 / 당첨 결제 모두 확인해주세요
- [x] 챌린지 시작 전에는 상품 수량, 챌린지 진행 기간 동안에는 잔여수량으로 표시됩니다. 반영해주세요
- [x] 마이챌린지 QR 상세 페이지는 챌린지 리스트에서의 상세 페이지와 순서가 다릅니다. 마이챌린지 QR 상세 페이지에서는 정보 목록이 다음과 같습니다: 챌린지 현황판 -> 체크인포인트 -> qr맵 -> 챌린지 정보 -> 수령지정보 -> 브랜드 정보 순서입니다
- [x] 마이챌린지 중 참가 중 & 진행 중인 챌린지가  있음에도 유저가 챌린지를 아직 카운트하고 있는 챌린지가 없는 경우: 下記リストより歩数をカウントするチャレンジを選択してください

**Comment by Hyungseok-Seong** [comment]
걸음 수 카운트가 가능/불가능한 경우가 챌린지의 종류, 챌린지 진행 타임에 따라 다릅니다. 확인 부탁드립니다.

**Comment by Hyungseok-Seong** [comment]
- [ ] 마이챌린지에서 챌린지 리스트들간 영역이 서로 겹치도록 나옵니다.

![image_3ac26ff](https://user-images.githubusercontent.com/34014924/34026127-4525f2fe-e197-11e7-8d28-ecde5d7a7ff9.jpg)

**Comment by Hyungseok-Seong** [comment]
마이챌린지-QR챌린지 상세 페이지. 챌린지 진행 중인 상황

- [ ] QR 버튼 위의 'QRチェックイン中' 에서 QR이 빠집니다.
- [ ] 하단의 빨간색 '챌린지 진행중' 버튼은 QR챌린지 진행중에 필요 없습니다.
- [ ] 남은 QR 부분 확인 부탁드립니다
- [ ] 이 페이지에서 잔여수량은 000/000 형태로 표시됩니다.

**Comment by Hyungseok-Seong** [comment]
- [ ] 마이챌린지 QR 상세 페이지에서, 챌린지 진행 중인 경우에는 챌린지 현황판(프로그레스바, 목표 qr, 남은 qr, 타임리미트, 잔여수량) 하단에 체크인 포인트가 먼저 나옵니다. (h01_mychallenge_detail_qr2 를 확인해 주세요)
- [ ] 위에 덧붙여, 챌린지 현황판 -> 체크인포인트 -> qr맵 -> 챌린지 정보 -> 수령지정보 -> 브랜드 정보 순서입니다
- [ ] 체크인포인트(チェクインポイント) 옆 아이콘은 map_icon 으로 변경해주세요.
- [ ] 챌린지 정보에서 " チャレンジタイプ  " ->  タイプ (타입) 으로 변경해주세요.

![s_7146001728546](https://user-images.githubusercontent.com/34014924/34027662-7f40482c-e1a1-11e7-8ca4-7a50b65028aa.jpg)

**Comment by Hyungseok-Seong** [comment]
QR챌린지 진행 중

- [ ] 마이챌린지-상세페이지에서 QR 체크인 포인트들은 QR 스캔과 동시에 체크 표시가 되어야 합니다.

![s_7160613641323](https://user-images.githubusercontent.com/34014924/34085402-aa14b522-e3d3-11e7-988f-f558011795a2.jpg)

**Comment by Hyungseok-Seong** [comment]
- [ ] 개인챌린지: 목표 걸음 수만큼 걸음 수를 카운트하여 챌린지를 달성한 경우 마이챌린지-카운트 섹션에서 해당 챌린지는 빠져나와야 함

**Comment by Hyungseok-Seong** [comment]
- [ ] 추천 챌린지 클릭이 안 되고 있습니다.

**Comment by Hyungseok-Seong** [comment]
- 챌린지 참가 신청 후, 마이챌린지-참가중인 챌린지에 진입했을 때, 챌린지 리스트에 중복되는 챌린지가
 나타나는 문제 

![list error](https://user-images.githubusercontent.com/34014924/34547860-842cd81e-f141-11e7-8630-05daf0fcfb88.jpg)

**Comment by Hyungseok-Seong** [comment]
- 마이챌린지 중 참가 중 & 진행 중인 챌린지가  있음에도 유저가 챌린지를 아직 카운트하고 있는 챌린지가 없는 경우: 下記リストより歩数をカウントするチャレンジを選択してください

**Comment by applicatteam** [comment]
- [ ] 챌린지 참여하지 않은 경우, 챌린지에 참여하고 있어도 걸음 수를 적립할 수 없는 경우 안내 멘트가 달라야 함 확인 요망
- [ ] 챌린지 카운트 버튼이 적용되는 챌린지/적용되지 않는 챌린지가 확실하게 정해져 있는데 반영되지 않았음
- [ ] 챌린지 타임라인에 따른 화면 및 안내 멘트가 기획과 다릅니다. 챌린지 시작 전 / 진행 / 결제 / 추첨 / 당첨 결제 모두 확인해주세요
- [ ] 챌린지 시작 전에는 상품 수량, 챌린지 진행 기간 동안에는 잔여수량으로 표시됩니다. 반영해주세요
- [ ] 마이챌린지 QR 상세 페이지는 챌린지 리스트에서의 상세 페이지와 순서가 다릅니다. 마이챌린지 QR 상세 페이지에서는 정보 목록이 다음과 같습니다: 챌린지 현황판 -> 체크인포인트 -> qr맵 -> 챌린지 정보 -> 수령지정보 -> 브랜드 정보 순서입니다
- [ ] 마이챌린지 중 참가 중 & 진행 중인 챌린지가  있음에도 유저가 챌린지를 아직 카운트하고 있는 챌린지가 없는 경우: 下記リストより歩数をカウントするチャレンジを選択してください
- [ ] QR 버튼 위의 'QRチェックイン中' 에서 QR이 빠집니다.
- [ ] 하단의 빨간색 '챌린지 진행중' 버튼은 QR챌린지 진행중에 필요 없습니다.
- [ ] 남은 QR 부분 확인 부탁드립니다
- [ ] 이 페이지에서 잔여수량은 000/000 형태로 표시됩니다.
- [ ] 마이챌린지-상세페이지에서 QR 체크인 포인트들은 QR 스캔과 동시에 체크 표시가 되어야 합니다.
- [ ] 개인챌린지: 목표 걸음 수만큼 걸음 수를 카운트하여 챌린지를 달성한 경우 마이챌린지-카운트 섹션에서 해당 챌린지는 빠져나와야 함
- [ ] 추천 챌린지 클릭이 안 되고 있습니다.
- [ ] 마이챌린지 중 참가 중 & 진행 중인 챌린지가 있음에도 유저가 챌린지를 아직 카운트하고 있는 챌린지가 없는 경우: 下記リストより歩数をカウントするチャレンジを選択してください
- [ ] 챌린지 참가 신청 후, 마이챌린지-참가중인 챌린지에 진입했을 때, 챌린지 리스트에 중복되는 챌린지가
나타나는 문제
