### ISSUE TITLE
홈 화면

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#28]
- [x] (171215 부가 설명 하단 참고) 챌린지 달성 시 걸음 수 카운트가 비활성화되어야 함: 챌린지 달성 시 걸음 수 카운트가 비활성화되어야 합니다.(카운트 버튼이 비활성화되고, 해당 챌린지는 '달성'한 것이므로, 유저의 챌린지 진행 타임라인에서 '진행 중 -> 결제'로 변경됩니다.)
- [x]  카운트 중인 챌린지가 홈 화면에서 가장 먼저 보여야 합니다. 그러나 이는 걸음 수 카운트가 가능한 챌린지로 한정됩니다. 걸음 수 카운트가 가능한 챌린지들 중 카운트 중인 챌린지여야 합니다. 현재는 걸음 수 카운트가 불가한 챌린지에도 카운트가 가능하도록 적용되어 있습니다. 덧붙여, '카운트 가능한 챌린지'란, 유저가 참가한 개인챌린지 중 admin에서 입력한 챌린지 진행 기간에 들어온 경우를 의미합니다.

**Comment by Hyungseok-Seong** [comment]
- [ ] 카운트 중인 챌린지가 홈 화면에서 가장 먼저 보여야 합니다. 그러나 이는 걸음 수 카운트가 가능한 챌린지로 한정됩니다. 걸음 수 카운트가 가능한 챌린지들 중 카운트 중인 챌린지여야 합니다. 현재는 걸음 수 카운트가 불가한 챌린지에도 카운트가 가능하도록 적용되어 있습니다.
- [ ] 챌린지 달성 시 걸음 수 카운트가 비활성화되어야 합니다.(카운트 버튼이 비활성화되고, 해당 챌린지는 '달성'한 것이므로, 유저의 챌린지 진행 타임라인에서 '진행 중 -> 결제'로 변경됩니다.)

**Comment by Hyungseok-Seong** [comment]
![s_7242464362969](https://user-images.githubusercontent.com/34014924/34472217-21db7c58-efa0-11e7-92d4-98c9677f4ebd.jpg)

- [ ] 참여한 챌린지 종료 후 홈 화면에 계속 뜨고 있는 화면입니다. 확인 부탁드립니다.

**Comment by Hyungseok-Seong** [comment]
![default](https://user-images.githubusercontent.com/34014924/34545438-5c1e04ee-f130-11e7-914b-7961cae1b77e.jpg)

- [ ] '결제불가'라는 한글이 입력된 버튼이 있습니다. 확인 후 변경 해주세요.

**Comment by Hyungseok-Seong** [comment]
- QR챌린지 진행 중: QR 코드 스캔 시 progress bar가 반대로 채워지고 있습니다.
![qr](https://user-images.githubusercontent.com/34014924/34546821-f34b8a04-f139-11e7-80f9-2159da7f37d5.jpg)

**Comment by Hyungseok-Seong** [comment]
- QR챌린지 달성시: 챌린지를 달성했음에도 리워드를 획득할 수 없는 문제 발생

![qr 1](https://user-images.githubusercontent.com/34014924/34546830-100ba9da-f13a-11e7-9905-dc4867cbca20.jpg)
![qr](https://user-images.githubusercontent.com/34014924/34546831-109b73da-f13a-11e7-9074-56a9442a7c4a.jpg)

**Comment by Hyungseok-Seong** [comment]
- 리워드 잔여 수량 표기 문제: 잔여수량/총수량 표기에서, 잔여수량이 총수량보다 많이 표시되는 문제가 있습니다.

![reward error](https://user-images.githubusercontent.com/34014924/34546871-41fe3ce6-f13a-11e7-8cb0-0c593bd2c3f0.jpg)

**Comment by applicatteam** [comment]
- [ ] (171215 부가 설명 하단 참고) 챌린지 달성 시 걸음 수 카운트가 비활성화되어야 함: 챌린지 달성 시 걸음 수 카운트가 비활성화되어야 합니다.(카운트 버튼이 비활성화되고, 해당 챌린지는 '달성'한 것이므로, 유저의 챌린지 진행 타임라인에서 '진행 중 -> 결제'로 변경됩니다.)
- [ ]  카운트 중인 챌린지가 홈 화면에서 가장 먼저 보여야 합니다. 그러나 이는 걸음 수 카운트가 가능한 챌린지로 한정됩니다. 걸음 수 카운트가 가능한 챌린지들 중 카운트 중인 챌린지여야 합니다. 현재는 걸음 수 카운트가 불가한 챌린지에도 카운트가 가능하도록 적용되어 있습니다. 덧붙여, '카운트 가능한 챌린지'란, 유저가 참가한 개인챌린지 중 admin에서 입력한 챌린지 진행 기간에 들어온 경우를 의미합니다.
- [ ] 카운트 중인 챌린지가 홈 화면에서 가장 먼저 보여야 합니다. 그러나 이는 걸음 수 카운트가 가능한 챌린지로 한정됩니다. 걸음 수 카운트가 가능한 챌린지들 중 카운트 중인 챌린지여야 합니다. 현재는 걸음 수 카운트가 불가한 챌린지에도 카운트가 가능하도록 적용되어 있습니다.
- [ ] 챌린지 달성 시 걸음 수 카운트가 비활성화되어야 합니다.(카운트 버튼이 비활성화되고, 해당 챌린지는 '달성'한 것이므로, 유저의 챌린지 진행 타임라인에서 '진행 중 -> 결제'로 변경됩니다.)
