### ISSUE TITLE
리워드, 보너스

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#29]
- [x] 리워드 상세 페이지에서 챌린지 상세 버튼 클릭 시 해당 챌린지의 상세 페이지로 이동해야 하지만 이동 없음

**Comment by Hyungseok-Seong** [comment]
- [ ] 보너스 30k 버튼: 友達を招待 로 변경되어야 합니다.
- [ ] 보너스 15k 버튼: フィードバック共有 로 변경되어야 합니다.

![bonus](https://user-images.githubusercontent.com/34014924/34545889-635ef56c-f133-11e7-8417-6bdd0f8dfbba.jpg)

**Comment by applicatteam** [comment]
- [ ] 리워드 상세 페이지에서 챌린지 상세 버튼 클릭 시 해당 챌린지의 상세 페이지로 이동해야 하지만 이동 없음

**Comment by Hyungseok-Seong** [comment]
확인했습니다.

![1](https://user-images.githubusercontent.com/34014924/35367787-9048bcac-01c3-11e8-9b21-f6b1ef83f184.jpeg)
![2](https://user-images.githubusercontent.com/34014924/35367788-906f5de4-01c3-11e8-9c4b-25839e3b20e7.jpeg)
