### ISSUE TITLE
Bonus 화면

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#3]
![image](https://user-images.githubusercontent.com/14939610/33247030-53047fc2-d35e-11e7-8849-a469ee511a08.png)

- [x] 상단의 폰트크기와 서브텍스트의 폰트 사이즈가 디자인한 것보다 더 커보이는데요. 폰트크기 확인부탁드립니다.

- [x] 보너스표시 왼쪽아래부분 카운트뱃지의 위치가 선에 너무 아슬아슬 걸려있는것 같습니다. 조금 위로 올려주세요.

- [x] 기존 디자인에는 3K보너스 박스 아래쪽의 #2FB2C4 컬러의 선이 있습니다. 확인부탁드립니다.

**Comment by gracemj** [comment]
@applicatteam 👍

**Comment by applicatteam** [comment]
이슈가 없다면 닫아주세요

**Comment by gracemj** [comment]
- [ ] 안드로이드 기기에서 각 보너스의 회색의 서브 텍스트가  흰박스의 우측에 여백없이 붙어버립니다.

- [ ] 버튼의 텍스트의 자간을 줄여주세요

**Comment by applicatteam** [comment]
* 버튼의 텍스트의 자간을 줄여주세요
![image](https://user-images.githubusercontent.com/15938046/35089298-d784c024-fc79-11e7-9792-8d7c00906c3f.png)

**Comment by applicatteam** [comment]
안드로이드 기기에서 각 보너스의 회색의 서브 텍스트가 흰박스의 우측에 여백없이 붙어버립니다.
![image](https://user-images.githubusercontent.com/15938046/35090095-0e11568c-fc7c-11e7-931d-048a5cda7159.png)
서브텍스트가 길어졌을 때 우측여백이 없는걸 말씀하시는건가요?

넘쳤을 때 이렇게 안넘어가게 하면 되는건가요?
![image](https://user-images.githubusercontent.com/15938046/35090176-35cc9e7a-fc7c-11e7-92ee-ffbc60b3141a.png)

**Comment by applicatteam** [comment]
이슈가 없다면 닫아주세요

**Comment by gracemj** [comment]
![image](https://user-images.githubusercontent.com/14939610/35136331-5174ea56-fd26-11e7-9a3e-5f805d62f3d5.png)

**Comment by applicatteam** [comment]
수정한 스크린샷 위에 업로드했습니다.

**Comment by gracemj** [comment]
안드로이드에서 저렇게 보이는 문제도 수정이 되었나요?

**Comment by applicatteam** [comment]
화면이 작은 기기의 경우 텍스트가 아래로 내려갑니다.

**Comment by gracemj** [comment]
@applicatteam 텍스트가 내려가는건 문제가 아닌데요 안드로이드 기기에서 우측에 여백없이 붙는걸 말씀드린겁니다.

**Comment by applicatteam** [comment]
그건 수정되었습니다.
