### ISSUE TITLE
notification

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#30]
- [x] 현재 noti에 있는 챌린지 안내 클릭 시 해당 챌린지의 상세 페이지로 이동해야하지만 챌린지 리스트로 이동하고 있음.
- [x] 현재 noti 작동하지 않고 있음

**Comment by Hyungseok-Seong** [comment]
- 현재 noti 작동하지 않고 있음

**Comment by applicatteam** [comment]
- [ ] 현재 noti에 있는 챌린지 안내 클릭 시 해당 챌린지의 상세 페이지로 이동해야하지만 챌린지 리스트로 이동하고 있음.
- [ ] 현재 noti 작동하지 않고 있음
