### ISSUE TITLE
기타

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#32]
- [x]  디바이스 회전시 화면이 wide screen으로 표시됨. 세로형 화면으로 고정 요망
- [x]  앱 종료 후 데이터 끄고 다시 켜는 경우, 참가 중이던 챌린지에서 빠짐. 프로필 정보(성별, 주소, 출생년도) 역시 모두 값이 빠짐. 하지만, 이 조건에서 챌린지 리스트에서 챌린지 참가가 가능함
- [x]  2 개의 개인 챌린지 참가 중인 경우, 홈에서는 2개의 챌린지가 표시되지만, 마이챌린지에서는 한 개의 챌린지만 나타나는 경우도 발생함

**Comment by applicatteam** [comment]
- [ ]  디바이스 회전시 화면이 wide screen으로 표시됨. 세로형 화면으로 고정 요망
- [ ]  앱 종료 후 데이터 끄고 다시 켜는 경우, 참가 중이던 챌린지에서 빠짐. 프로필 정보(성별, 주소, 출생년도) 역시 모두 값이 빠짐. 하지만, 이 조건에서 챌린지 리스트에서 챌린지 참가가 가능함
- [ ]  2 개의 개인 챌린지 참가 중인 경우, 홈에서는 2개의 챌린지가 표시되지만, 마이챌린지에서는 한 개의 챌린지만 나타나는 경우도 발생함
