### ISSUE TITLE
profile 입력란

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#34]
- [x] 출생년도인 出生年も 를  生まれた年 로 변경 부탁드립니다.
- [x] 성별은 性別 로 변경해주세요
- [x] 우편번호 입력 시 옆의 주소검색 버튼이 활성화되는 것이 잘 눈에 뜨이지 않습니다.
- [x] 주소 검색 버튼의 글자가 줄 바꿈이 되어있습니다. 확인해주세요.

![image_d339e0b](https://user-images.githubusercontent.com/34014924/34025636-3a89a0e6-e194-11e7-8ddc-24141d647eeb.jpg)

**Comment by applicatteam** [comment]
- [x] 출생년도인 出生年も 를  生まれた年 로 변경 부탁드립니다.
- [x] 성별은 性別 로 변경해주세요
- [x] 우편번호 입력 시 옆의 주소검색 버튼이 활성화되는 것이 잘 눈에 뜨이지 않습니다.
- [ ] 주소 검색 버튼의 글자가 줄 바꿈이 되어있습니다. 확인해주세요.
