### ISSUE TITLE
알림

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#35]
- [x] admin에서 알림을 통해 메시지 전송하면, 푸시 영역에서 보이지 않습니다.

**Comment by applicatteam** [comment]
- [ ] admin에서 알림을 통해 메시지 전송하면, 푸시 영역에서 보이지 않습니다.

**Comment by Hyungseok-Seong** [comment]
확인되었습니다.


![admin push](https://user-images.githubusercontent.com/34014924/35368233-b5d872da-01c5-11e8-87b6-301b66e51c59.jpeg)
