### ISSUE TITLE
결제화면

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#37]
i00_payment1

- [ ] 결제금액 하단에 있는 '商品情報' 가 아니라 'コメント' 로 변경해 주세요.

![s_7178916533837](https://user-images.githubusercontent.com/34014924/34249492-3a6948a8-e67d-11e7-9274-4b4d59f0ec24.jpg)

**Comment by applicatteam** [comment]
- [ ] 결제금액 하단에 있는 '商品情報' 가 아니라 'コメント' 로 변경해 주세요.
