### ISSUE TITLE
회원가입시 프라이버시 및 이용규약 페이지: a04_join1+term1

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#38]
- [ ] privacy policy 문서의 내용과 terms of use 의 문서 내용이 함께 나와야 합니다. 파일의 내용이 업데이트 되었습니다. 첨부 파일을 확인해 주세요.

[プライバシーポリシー及び利用規約.zip](https://github.com/gracemj/getwalk/files/1581063/default.zip)

- [ ] menu -> 설정 -> 利用規約 및 プライバシーポリシー 부분도 업데이트 부탁드립니다.

**Comment by Hyungseok-Seong** [comment]
- [ ] menu -> 설정 -> 利用規約 및 プライバシーポリシー 부분도 업데이트 부탁드립니다.

**Comment by applicatteam** [comment]
- [ ] privacy policy 문서의 내용과 terms of use 의 문서 내용이 함께 나와야 합니다. 파일의 내용이 업데이트 되었습니다. 첨부 파일을 확인해 주세요.
- [ ] menu -> 설정 -> 利用規約 및 プライバシーポリシー 부분도 업데이트 부탁드립니다.

**Comment by Hyungseok-Seong** [comment]
회원 가입시 표시되는 Privacy policy와 terms of use의 경우 줄바꿈이 app 에서는 적용되어 있지 않습니다.
