### ISSUE TITLE
홈 화면 배경컬러

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#4]
![image](https://user-images.githubusercontent.com/14939610/33247175-657f8d62-d35f-11e7-9781-80d9fc29d873.png)

- [x] 배경색으로 적용 된 컬러값이 어둡습니다. F8F9FA으로 적용부탁드립니다. 

- [x] 상단의 바영역도 같은 배경색 F8F9FA으로 적용해 주세요.

**Comment by gracemj** [comment]
@applicatteam 👍

**Comment by applicatteam** [comment]
이슈가 없다면 닫아주세요

**Comment by applicatteam** [comment]
확인 및 수정 완료되었습니다
