### ISSUE TITLE
피드백 작성

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#40]
- [x] Bonus 에서 15k보너스 걸음 쿠폰 받기 버튼이 활성화되기 위해서는 유저가 하나의 챌린지를 완료한 경우여야 함
 - [x] 15k 보너스 걸음 쿠폰 받기 버튼 클릭시 navigation: 마이챌린지->종료된 챌린지 리스트 입니다. (현재 진행 중 챌린지로 이동합니다)
- [x] 마이챌린지-종료된챌린지-챌린지 상세 페이지에서, '피드백을 아직 작성하지 않은 경우' 나오는 버튼은 피드백 작성하기 버튼입니다.
- [x] 피드백 작성 페이지에서 공유하기 버튼 클릭 후 -> SNS (fb, insta, twitter) 클릭 해도 해당 SNS 채널이 열리지 않고 있습니다.
- [x] 피드백 작성 후 '확인' 버튼이 클릭되지 않습니다.

**Comment by Hyungseok-Seong** [comment]
- [ ] 15k 보너스 걸음 쿠폰 받기 버튼 클릭시 navigation: 마이챌린지->종료된 챌린지 리스트 입니다. (현재 진행 중 챌린지로 이동합니다)
- [ ] 마이챌린지-종료된챌린지-챌린지 상세 페이지에서, '피드백을 아직 작성하지 않은 경우' 나오는 버튼은 피드백 작성하기 버튼입니다.
- [ ] 피드백 작성 페이지에서 공유하기 버튼 클릭 후 -> SNS (fb, insta, twitter) 클릭 해도 해당 SNS 채널이 열리지 않고 있습니다.

**Comment by Hyungseok-Seong** [comment]
- 피드백 작성 후 '확인' 버튼이 클릭되지 않습니다.

**Comment by applicatteam** [comment]
- [ ] Bonus 에서 15k보너스 걸음 쿠폰 받기 버튼이 활성화되기 위해서는 유저가 하나의 챌린지를 완료한 경우여야 함
 - [ ] 15k 보너스 걸음 쿠폰 받기 버튼 클릭시 navigation: 마이챌린지->종료된 챌린지 리스트 입니다. (현재 진행 중 챌린지로 이동합니다)
- [ ] 마이챌린지-종료된챌린지-챌린지 상세 페이지에서, '피드백을 아직 작성하지 않은 경우' 나오는 버튼은 피드백 작성하기 버튼입니다.
- [ ] 피드백 작성 페이지에서 공유하기 버튼 클릭 후 -> SNS (fb, insta, twitter) 클릭 해도 해당 SNS 채널이 열리지 않고 있습니다.
- [ ] 피드백 작성 후 '확인' 버튼이 클릭되지 않습니다.
- [ ] 15k 보너스 걸음 쿠폰 받기 버튼 클릭시 navigation: 마이챌린지->종료된 챌린지 리스트 입니다. (현재 진행 중 챌린지로 이동합니다)
- [ ] 마이챌린지-종료된챌린지-챌린지 상세 페이지에서, '피드백을 아직 작성하지 않은 경우' 나오는 버튼은 피드백 작성하기 버튼입니다.
- [ ] 피드백 작성 페이지에서 공유하기 버튼 클릭 후 -> SNS (fb, insta, twitter) 클릭 해도 해당 SNS 채널이 열리지 않고 있습니다.
- [ ] 피드백 작성 후 '확인' 버튼이 클릭되지 않습니다.

**Comment by applicatteam** [comment]
인스타그램 공유시 이미지 업로드 , 문자 복사후 확인
