### ISSUE TITLE
친구 앱 초대 공유하기

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#41]
[친구 앱초대 공유하기_170102.docx](https://github.com/gracemj/getwalk/files/1596552/_170102.docx)

- [x] 친구 앱초대 공유하기 메시지 멘트가 틀린 부분이 있어 수정했습니다. 번거롭게 해 드려서 죄송합니다. 업로드된 파일의 멘트로 변경해서 작업 부탁드립니다.
- [x] 친구 앱초대 - LINE으로 공유시 LINE이 열리지 않는 문제가 있습니다.
- [ ] 친구 앱초대 공유시 보여지는 이미지 파일이 뜨지 않고 있습니다.
- [x] 친구 앱초대 공유시 전달되는 텍스트 중 유저의 추천인코드 앞에 + 가 붙어 있습니다. 확인 후 수정해주세요.
- [ ] 친구 앱초대 공유하기 메시지 멘트에 줄바꿈 없이 나와있습니다. 첨부된 문서를 다시 확인해주세요.
- [ ] app 다운로드 링크 수정해 주세요.

**Comment by Hyungseok-Seong** [comment]
- [ ] 친구 앱초대 공유시 보여지는 이미지 파일이 뜨지 않고 있습니다.
![gw_share](https://user-images.githubusercontent.com/34014924/34472169-d20788b2-ef9e-11e7-85f8-358575c0b517.png)

**Comment by Hyungseok-Seong** [comment]
- 친구 앱초대 공유시 전달되는 텍스트 중 유저의 추천인코드 앞에 + 가 붙어 있습니다. 확인 후 수정해주세요.
- 앱초대 공유하기 메시지에 줄바꿈이 들어갈 수가 없나요?

![default](https://user-images.githubusercontent.com/34014924/34546368-bb16b1de-f136-11e7-9202-98097fc62fd7.jpg)

**Comment by Hyungseok-Seong** [comment]
- 친구 앱초대 공유하기 메시지 멘트에 줄바꿈 없이 나와있습니다. 첨부된 문서를 다시 확인해주세요.
- app 다운로드 링크 수정해 주세요.

**Comment by applicatteam** [comment]
- [x] 친구 앱초대 공유하기 메시지 멘트가 틀린 부분이 있어 수정했습니다. 번거롭게 해 드려서 죄송합니다. 업로드된 파일의 멘트로 변경해서 작업 부탁드립니다.
- [x] 친구 앱초대 - LINE으로 공유시 LINE이 열리지 않는 문제가 있습니다.
- [ ] 친구 앱초대 공유시 보여지는 이미지 파일이 뜨지 않고 있습니다.
- [x] 친구 앱초대 공유시 전달되는 텍스트 중 유저의 추천인코드 앞에 + 가 붙어 있습니다. 확인 후 수정해주세요.
- [ ] 친구 앱초대 공유하기 메시지 멘트에 줄바꿈 없이 나와있습니다. 첨부된 문서를 다시 확인해주세요.
- [ ] app 다운로드 링크 수정해 주세요.
