### ISSUE TITLE
누적 걸음 수 및 Level 변화

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#42]
- [ ] 누적 걸음 수는 '유저가 실제로 걸어서 GetWalk app에서 카운트된 걸음 수' + '보너스 걸음 쿠폰 획득'의 합입니다. 현재 실제로 걸어서 획득한 걸음 수가 반영되지 않고 있습니다.
- [ ] 30k 보너스 걸음 쿠폰 획득 시 level 정책에 따라  user 레벨이 2레벨로 변경되어야 하지만, 변경되지 않고 있습니다.
- [ ] 걸음 수는 100만 걸음 이상부터 k를 붙여 주세요. 10만 단위까지는 전부 숫자가 표시되도록 부탁드립니다.
 - [ ] 보너스 걸음 쿠폰을 획득하는 순간 유저의 누적 걸음 수에 카운트되어야 합니다. 현재는 보너스 걸음 쿠폰을 사용할 때만 반영되고 있습니다. 확인 부탁드립니다.
 - [ ] iOS의 경우 앱의 위치 정보 접근을 '앱을 사용하는 동안' 및  '항상' 중 '항상' 쓸 수 있도록 되어야 합니다. CBT 참가자들 대부분은 걸음 수 카운트가 되지 않는 문제를 제기하고 있습니다.

**Comment by Hyungseok-Seong** [comment]
- 보너스 걸음 쿠폰을 획득하는 순간 유저의 누적 걸음 수에 카운트되어야 합니다. 현재는 보너스 걸음 쿠폰을 사용할 때만 반영되고 있습니다. 확인 부탁드립니다.

**Comment by Hyungseok-Seong** [comment]
- iOS의 경우 앱의 위치 정보 접근을 '앱을 사용하는 동안' 및  '항상' 중 '항상' 쓸 수 있도록 되어야 합니다. CBT 참가자들 대부분은 걸음 수 카운트가 되지 않는 문제를 제기하고 있습니다.

**Comment by applicatteam** [comment]
- [ ] 누적 걸음 수는 '유저가 실제로 걸어서 GetWalk app에서 카운트된 걸음 수' + '보너스 걸음 쿠폰 획득'의 합입니다. 현재 실제로 걸어서 획득한 걸음 수가 반영되지 않고 있습니다.
- [ ] 30k 보너스 걸음 쿠폰 획득 시 level 정책에 따라  user 레벨이 2레벨로 변경되어야 하지만, 변경되지 않고 있습니다.
- [ ] 걸음 수는 100만 걸음 이상부터 k를 붙여 주세요. 10만 단위까지는 전부 숫자가 표시되도록 부탁드립니다.
 - [ ] 보너스 걸음 쿠폰을 획득하는 순간 유저의 누적 걸음 수에 카운트되어야 합니다. 현재는 보너스 걸음 쿠폰을 사용할 때만 반영되고 있습니다. 확인 부탁드립니다.
 - [ ] iOS의 경우 앱의 위치 정보 접근을 '앱을 사용하는 동안' 및  '항상' 중 '항상' 쓸 수 있도록 되어야 합니다. CBT 참가자들 대부분은 걸음 수 카운트가 되지 않는 문제를 제기하고 있습니다.
