### ISSUE TITLE
Quiz

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#43]
![quiz](https://user-images.githubusercontent.com/34014924/34472381-6796b7d6-efa4-11e7-932e-7e786b5fc0d2.jpg)

- [ ] 유저의 퀴즈 정답 입력을 받기 전까지는 답안 제출 버튼이 비활성화된 상태여야 합니다.
- [ ] 답을 입력한 뒤 답안 제출 버튼이 클릭되지 않고 있습니다.
- [ ] Quiz img 비율은 어떻게 맞추면 되나요?
- [ ] 유저가 퀴즈의 답안 입력 시, iOS에서는 답안 제출 버튼이 키보드에 가려져 있습니다. 확인 후 수정 부탁드립니다.

**Comment by applicatteam** [comment]
- [ ] 유저의 퀴즈 정답 입력을 받기 전까지는 답안 제출 버튼이 비활성화된 상태여야 합니다.
- [ ] 답을 입력한 뒤 답안 제출 버튼이 클릭되지 않고 있습니다.
- [ ] Quiz img 비율은 어떻게 맞추면 되나요?
- [ ] 유저가 퀴즈의 답안 입력 시, iOS에서는 답안 제출 버튼이 키보드에 가려져 있습니다. 확인 후 수정 부탁드립니다.
