### ISSUE TITLE
이메일 재입력 시 제목 색상

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#45]
- [ ] 이메일 재입력 시 제대로되어도 상단 제목이 레드 색상으로 보입니다.
![img_0549](https://user-images.githubusercontent.com/14939610/34511293-c6c01f0a-f09d-11e7-9f93-ac39d3b45089.png)

**Comment by applicatteam** [comment]
- [ ] 이메일 재입력 시 제대로되어도 상단 제목이 레드 색상으로 보입니다.
