### ISSUE TITLE
홈>QR챌린지 진행화면

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#5]
![image](https://user-images.githubusercontent.com/14939610/33247317-77c44002-d360-11e7-85e4-27b532036807.png)

- [x] QR진행화면의 상단은 위의 이미지와 같이 됩니다.

![image](https://user-images.githubusercontent.com/14939610/33247336-a154b5be-d360-11e7-8020-ebe023503660.png)

- [x] QR진행화면의 디자인확인 부탁드립니다. 진행버튼과 텍스트가 진행바의 위쪽으로 올라간것 같습니다.

- [x] 목표QR과 남은 QR의 숫자 폰트의 두께가 두껍습니다. 숫자폰트 크기도 확인부탁드립니다.

- [x] 진행바의 회색컬러값이 좀 진해보이는데 확인부탁드립니다.

**Comment by applicatteam** [comment]
QR진행화면의 상단은 위의 이미지와 같이 됩니다.

**Comment by applicatteam** [comment]
이슈가 없다면 닫아주세요
