### ISSUE TITLE
결제 이슈

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#52]
- [x] 리워드 결제가 완료되지 않은 시점에, 유저의 마이페이지에서 결제 내역에 기록되고 있습니다. 확인해 주세요. (imgs: payerror1 ~ payerror5)
- [x] 위의 경우에 덧붙여, 결제 내역에 기록될 때마다 해당 챌린지의 리워드 잔여 수량 역시 함께 줄어들고 있습니다.
- [x] 결제시 남기는 메모 부분에서 텍스트 입력 커서가 입력창을 벗어나는 문제
- [x] 리워드가 남아 있지만 재고 소진이라는 에러가 뜨는 문제

![payerror1](https://user-images.githubusercontent.com/34014924/34547813-3839afa4-f141-11e7-8390-1bb0f52055fc.jpg)
![payerror2](https://user-images.githubusercontent.com/34014924/34547814-38809216-f141-11e7-910e-a9c18f52278c.jpg)
![payerror3](https://user-images.githubusercontent.com/34014924/34547816-38c90ff0-f141-11e7-8b4d-d7adc260454d.jpg)
![payerror4](https://user-images.githubusercontent.com/34014924/34547818-3910d10a-f141-11e7-9e1e-19963bf50bc0.jpg)
![payerror5](https://user-images.githubusercontent.com/34014924/34547819-395ac12a-f141-11e7-83af-7cbc8915cb87.jpg)

  ![pay memo](https://user-images.githubusercontent.com/34014924/34548405-447f7fb0-f145-11e7-9a26-dfb8e16735fd.jpg)

  ![reward stock error](https://user-images.githubusercontent.com/34014924/34549703-15848a1c-f14e-11e7-9634-64a4a7fcd9af.jpg)

**Comment by Hyungseok-Seong** [comment]
- 결제시 남기는 메모 부분에서 텍스트 입력 커서가 입력창을 벗어나는 문제

**Comment by applicatteam** [comment]
- [ ] 리워드 결제가 완료되지 않은 시점에, 유저의 마이페이지에서 결제 내역에 기록되고 있습니다. 확인해 주세요. (imgs: payerror1 ~ payerror5)
- [ ] 위의 경우에 덧붙여, 결제 내역에 기록될 때마다 해당 챌린지의 리워드 잔여 수량 역시 함께 줄어들고 있습니다.
- [ ] 결제시 남기는 메모 부분에서 텍스트 입력 커서가 입력창을 벗어나는 문제
- [ ] 리워드가 남아 있지만 재고 소진이라는 에러가 뜨는 문제

**Comment by applicatteam** [comment]
남은 상품 수 내려가는 문제점 확인

**Comment by applicatteam** [comment]
결제시 남기는 메모 부분에서 텍스트 입력 커서가 입력창을 벗어나는 문제
-> ios 버전 11.3에서 확인해야함
