### ISSUE TITLE
하단 메뉴바 아이콘 스타일

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#6]
![image](https://user-images.githubusercontent.com/14939610/33247578-6f85e2ae-d362-11e7-9cc9-4f80465d0ad0.png)

- [x] 각 메뉴 아이콘의 크기와 정렬이 기존 디자인과 다릅니다. 확인부탁드립니다.

**Comment by gracemj** [comment]
@applicatteam 👍

**Comment by applicatteam** [comment]
이슈가 없다면 닫아주세요

**Comment by gracemj** [comment]
제플린보고 다시 정확하게 확인부탁드립니다 👍

**Comment by applicatteam** [comment]
![image](https://user-images.githubusercontent.com/15938046/35095737-f0655c8a-fc8c-11e7-990b-602379537dc4.png)

**Comment by applicatteam** [comment]
![image](https://user-images.githubusercontent.com/15938046/35095976-dbdcd580-fc8d-11e7-9dbe-fde2699f92fc.png)

![image](https://user-images.githubusercontent.com/15938046/35095986-e1ddbfe4-fc8d-11e7-9cba-d45563814243.png)

![image](https://user-images.githubusercontent.com/15938046/35095990-e4d5a3ce-fc8d-11e7-8847-b207c51c16a8.png)

![image](https://user-images.githubusercontent.com/15938046/35095996-e80a961c-fc8d-11e7-8149-7b378665ed4d.png)

![image](https://user-images.githubusercontent.com/15938046/35096001-ebcabfca-fc8d-11e7-9cee-4fa744281f83.png)

이미지 크기가 다 달라서 다르게 보일 수 있습니다. 확인부탁드립니다.

**Comment by applicatteam** [comment]
이슈가 없다면 닫아주세요
