### ISSUE TITLE
타이머 UI 

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#62]
![img_0609](https://user-images.githubusercontent.com/14939610/34590959-74ab2910-f1fd-11e7-8414-7c8fe8954d2e.gif)

- [ ] 홈이나 챌린지 상세부분의 타이머가 있는 부분이 숫자가 바뀔 때마다 글자와 옆의 UI까지 움직입니다. 숫자영역과 텍스트 영역이 고정되어야할 것 같습니다.

**Comment by applicatteam** [comment]
- [ ] 홈이나 챌린지 상세부분의 타이머가 있는 부분이 숫자가 바뀔 때마다 글자와 옆의 UI까지 움직입니다. 숫자영역과 텍스트 영역이 고정되어야할 것 같습니다.
