### ISSUE TITLE
유저의 챌린지 목표 달성 현황 변경 '남은' -> '획득' 변경

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#65]
- [x] 개인챌린지: 남은 걸음수를 '지금까지 걸은 걸음 수'로 변경합니다. '획득 걸음'으로 명명합니다. 獲得歩数
- [x] QR챌린지: 남은 QR 코드를 '지금까지 스캔한 QR 코드 수'로 변경합니다. '획득 QR'으로 명명합니다. 獲得QR

**Comment by applicatteam** [comment]
- [ ] 개인챌린지: 남은 걸음수를 '지금까지 걸은 걸음 수'로 변경합니다. '획득 걸음'으로 명명합니다. 獲得歩数
- [ ] QR챌린지: 남은 QR 코드를 '지금까지 스캔한 QR 코드 수'로 변경합니다. '획득 QR'으로 명명합니다. 獲得QR
