### ISSUE TITLE
ADMIN 챌린지 진행 기간 입력시 다른 날짜로 저장되는 이슈

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#69]
- [ ] admin에서 챌린지 생성시, 챌린지 진행 기간 입력시 endDate 날짜가 다른 날짜로 저장되는 이슈 발생 중

**Comment by applicatteam** [comment]
- [ ] admin에서 챌린지 생성시, 챌린지 진행 기간 입력시 endDate 날짜가 다른 날짜로 저장되는 이슈 발생 중
