### ISSUE TITLE
마이리워드 화면 스타일

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#7]
![image](https://user-images.githubusercontent.com/14939610/33247761-cce5726a-d363-11e7-89cf-93f4cbc32bd5.png)

- [x] 상단메뉴바 아래 선 컬러가 다릅니다.

- [x] 각 리스트에 들어가는 이미지는 상품의 이미지를 흰배경에 넣을 예정입니다. 그래서 이미지의 우측에 세로 선이 그레이로 들어갑니다. 이부분 확인부탁드립니다.

- [x] 각 리스트의 우측상단의 딱지는 수령여부, 수령기간을 보여줍니다. 그래서 상품을 수령하지 않은 모든 경우(受取済み외) 에는 배경이 F74646의 붉은 컬러로 적용됩니다. 

- [x] 리스트 내의 텍스트 폰트 사이즈가 좀 커보이는데 이부분 확인부탁드립니다.

**Comment by applicatteam** [comment]
리워드 이미지 확인

**Comment by applicatteam** [comment]
![image](https://user-images.githubusercontent.com/15938046/35096334-24502ce4-fc8f-11e7-89a3-a9d24d5f6e08.png)

**Comment by applicatteam** [comment]
이슈가 없다면 닫아주세요
