### ISSUE TITLE
설정 부분의 '알람' 일본어표기 

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#71]
![image](https://user-images.githubusercontent.com/14939610/35022172-e6805ff0-fb77-11e7-862c-43e33a5f9bd2.png)

- [ ] **アラム**  -->   **アラーム**

**Comment by applicatteam** [comment]
![image](https://user-images.githubusercontent.com/15938046/35022784-14a82de2-fb7b-11e7-9e69-0dfd9d10bb75.png)

수정했습니다.

**Comment by gracemj** [comment]
첨부 된 이미지는 변경이 안되어있는데요? 업데이트 이후에 확인가능한가요?

**Comment by applicatteam** [comment]
アラム --> アラーム
이렇게 수정했는데 아닌가요?

**Comment by applicatteam** [comment]
アラム가 들어간 모든걸 수정해야 되는건가요?

**Comment by gracemj** [comment]
네 맞습니다

**Comment by applicatteam** [comment]
다음부턴 자세히 부탁드리겠습니다. 저희는 일본어를 모릅니다.

**Comment by applicatteam** [comment]
![image](https://user-images.githubusercontent.com/15938046/35023182-e75a53e0-fb7c-11e7-8bd6-d18c177e5cd6.png)

수정했습니다.

**Comment by gracemj** [comment]
네, 확인했습니다

**Comment by applicatteam** [comment]
오늘 수정되어 적용 및 확인 했던 사항입니다. close  부탁드립니다.

**Comment by gracemj** [comment]
@applicatteam 수고하셨습니다.
