### ISSUE TITLE
마이페이지 UI

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#72]
![01](https://user-images.githubusercontent.com/14939610/35027126-427c18f2-fb92-11e7-8c5f-cd38a905f851.gif)

- [ ] 우측메뉴에서 마이페이지로 갔을 때 보여지는 화면에서 상단 색있는 부분의 UI가 위로 움직입니다.

**Comment by applicatteam** [comment]
- [ ] 우측메뉴에서 마이페이지로 갔을 때 보여지는 화면에서 상단 색있는 부분의 UI가 위로 움직입니다.
