### ISSUE TITLE
참여 중인 챌린지가 3개이지만, 홈 화면에서 표시되지 않는 문제

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#73]
- [x] 참여 중인 챌린지가 QR1, 개인1,2 총 3개이지만, 홈 화면에서 개인챌린지 한 개만 표시되고 있으며, indicator가 활성화되어있지만 swipe를 통해 넘어가지 않고 있습니다.

![default](https://user-images.githubusercontent.com/34014924/35027407-e2f8457a-fb93-11e7-8595-72e801dcb454.jpg)
![2](https://user-images.githubusercontent.com/34014924/35027408-e4181390-fb93-11e7-8562-df84a9994db2.jpg)

**Comment by applicatteam** [comment]
- [ ] 참여 중인 챌린지가 QR1, 개인1,2 총 3개이지만, 홈 화면에서 개인챌린지 한 개만 표시되고 있으며, indicator가 활성화되어있지만 swipe를 통해 넘어가지 않고 있습니다.
