### ISSUE TITLE
결제 화면에서 리워드 이미지가 보이지 않습니다.

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#74]
- [x] 결제 화면에서 리워드 이미지가 보이지 않습니다.

![no](https://user-images.githubusercontent.com/34014924/35027485-5698d38c-fb94-11e7-9f65-d137c2b645ae.jpg)

**Comment by applicatteam** [comment]
- [ ] 결제 화면에서 리워드 이미지가 보이지 않습니다.
