### ISSUE TITLE
할인율 표시 오기

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#76]
- [x] 개인 챌린지 결제 화면: 유저가 목표 걸음 대비 달성한 만큼 할인 받는 '할인율' 표시값이 잘못 나타나 있습니다.

![default](https://user-images.githubusercontent.com/34014924/35028269-911fc9a8-fb98-11e7-8d45-f7adb554548a.jpg)

**Comment by applicatteam** [comment]
- [ ] 개인 챌린지 결제 화면: 유저가 목표 걸음 대비 달성한 만큼 할인 받는 '할인율' 표시값이 잘못 나타나 있습니다.
