### ISSUE TITLE
마이 챌린지> 종료된 챌린지 화면 스타일

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#8]
![image](https://user-images.githubusercontent.com/14939610/33248046-eed1bf8a-d365-11e7-9e99-22f267a17e74.png)

- [x] 위 이미지에서  진행중 챌린지/ 종료된 챌린지의 폰트 두께가 두껍습니다. 그리고 선택전환시 텍스트 위치도 어긋나보입니다. 

![image](https://user-images.githubusercontent.com/14939610/33248073-2b6fc360-d366-11e7-9cc7-594804883616.png)

- [x] 각 리스트의 폰트 사이즈와 스타일 확인 부탁드립니다.

- [x] 피드백 작성된 것과 피드백 작성가능한 부분의 버튼 컬러가 다릅니다. 확인부탁드립니다.

**Comment by applicatteam** [comment]
목록 아래 그림자 적용 , 이미지 사이즈 확인

**Comment by applicatteam** [comment]
이슈가 없다면 닫아주세요
