### ISSUE TITLE
결제시 할인율 및 할인금액 둘 다 잘못 표기 및 계산도 틀린 경우 발생

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#80]
- [ ] 결제시 할인율 및 할인금액 둘 다 잘못 표기 및 계산도 틀린 경우 발생

![default](https://user-images.githubusercontent.com/34014924/35030023-f5c643a2-fba0-11e7-8786-27340a71c3d9.jpg)

**Comment by applicatteam** [comment]
- [ ] 결제시 할인율 및 할인금액 둘 다 잘못 표기 및 계산도 틀린 경우 발생

**Comment by Hyungseok-Seong** [comment]
180320
테스트 시나리오에 따라 함께 확인하겠습니다.
현재는 나타나지 않는 현상이므로 우선 닫겠습니다.
