### ISSUE TITLE
참여 중인 개인 챌린지 홈 화면 프로그레스바 없음

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#86]
- [ ] 참여 중인 개인 챌린지, 아래 이미지와 같이 프로그레스바가 없는 형태로 표시되고 있습니다. 180118 해당 버그 사항이 재현된 상황을 파악했습니다: 여러 개의 챌린지 참여 중인 유저
 입장이 전제됩니다. 홈 화면에서 결제 버튼을 눌러 결제창으로 들어갑니다. 결제창에서 다시 홈 화면으로 돌아옵니다. 홈 화면에서 다른 챌린지들을 확인할 수 있습니다. 이 때 나타나는 챌린지의 프로그레스바가 다 사라진 채 홈 화면에 표시됩니다.

![home](https://user-images.githubusercontent.com/34014924/35032265-a6786aa6-fba9-11e7-9f48-ecf855395926.jpg)

**Comment by applicatteam** [comment]
- [ ] 참여 중인 개인 챌린지, 아래 이미지와 같이 프로그레스바가 없는 형태로 표시되고 있습니다. 180118 해당 버그 사항이 재현된 상황을 파악했습니다: 여러 개의 챌린지 참여 중인 유저
 입장이 전제됩니다. 홈 화면에서 결제 버튼을 눌러 결제창으로 들어갑니다. 결제창에서 다시 홈 화면으로 돌아옵니다. 홈 화면에서 다른 챌린지들을 확인할 수 있습니다. 이 때 나타나는 챌린지의 프로그레스바가 다 사라진 채 홈 화면에 표시됩니다.

**Comment by Hyungseok-Seong** [comment]
180320
테스트 시나리오에 따라 함께 확인하겠습니다.
