### ISSUE TITLE
마이챌린지> 진행중 챌린지 스타일

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#9]
![image](https://user-images.githubusercontent.com/14939610/33248224-4573fb0e-d367-11e7-80ad-c91cc212411c.png)

- [x] 상단의 적립변경 아이콘 크기와 폰트 사이즈 크기가 큰것같아요. 확인 부탁드립니다.

- [x] 리스트의 폰트 스타일을 전체적으로 확인부탁드립니다. 폰트 사이즈, 여백 등 디자인 시안과 차이가 있습니다.

- [x] 리스트하단의 챌린지 정보부분도 아이콘과 폰트 컬러가 다르게 적용됩니다. 폰트가 좀 더 밝은 컬러입니다. 디자인시안보다 이부분이 더 빽빽해보이는데 아이콘 사이즈와 여백도 확인부탁드립니다.

- [x] 리스트 좌측상단의 할인율 딱지안의 폰트가 상하로 중앙에 정렬이 안된것 같습니다.

- [x] 리스트 박스마다 아래로 그림자가 적용이 안되었습니다.

**Comment by applicatteam** [comment]
이슈가 없다면 닫아주세요
