### ISSUE TITLE
개인챌린지상세페이지-시간표시 에러

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#95]
- [x] 개인챌린지상세페이지-시간표시 에러

![s_7326346389856](https://user-images.githubusercontent.com/34014924/35050982-83123522-fbe7-11e7-802a-10807ab2079d.jpg)

**Comment by applicatteam** [comment]
- [ ] 개인챌린지상세페이지-시간표시 에러
