### ISSUE TITLE
admin-user management 결제 횟수

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#98]
- [x] admin- user management에서 유저들의 결제 횟수가 기록되어 있습니다. 해당 수치가 '실제로 결제된 횟수'인지, '결제 화면에 들어간 횟수'인지 불분명해 보입니다. 실제로, Smart Routine에서는 결제 창에만 들어간 적은 있어도, 결제가 이루어진 적은 없기 때문입니다. applicat 쪽에서 정의한 결제 횟수가 어떤 것인지 알려주세요.

![admin-payment](https://user-images.githubusercontent.com/34014924/35075177-f5b522ae-fc34-11e7-9cb3-7b9b23544153.PNG)

**Comment by applicatteam** [comment]
- [ ] admin- user management에서 유저들의 결제 횟수가 기록되어 있습니다. 해당 수치가 '실제로 결제된 횟수'인지, '결제 화면에 들어간 횟수'인지 불분명해 보입니다. 실제로, Smart Routine에서는 결제 창에만 들어간 적은 있어도, 결제가 이루어진 적은 없기 때문입니다. applicat 쪽에서 정의한 결제 횟수가 어떤 것인지 알려주세요.

**Comment by applicatteam** [comment]
실제 결제한 횟수를 보여줍니다

**Comment by Hyungseok-Seong** [comment]
오늘 전달해주시면 확인해보겠습니다.

**Comment by Hyungseok-Seong** [comment]
확인되었습니다.
